import '../models/dua_models.dart';

class DuaService {
  static List<DuaCategory> getCategories() {
    return [
      // 1. Daily Duas (Morning & Evening)
      DuaCategory(
        id: 'daily_duas',
        nameAr: 'الأدعية اليومية',
        nameEn: 'Daily Duas',
        nameBn: 'দৈনিক দোয়া',
        descriptionAr: 'أدعية الصباح والمساء والأعمال اليومية',
        descriptionEn: 'Morning, evening and daily activity duas',
        descriptionBn: 'সকাল, সন্ধ্যা এবং দৈনিক কাজের দোয়া',
        iconPath: '🌅',
        duas: [
          Dua(
            id: 'morning_remembrance',
            type: 'daily',
            titleAr: 'أذكار الصباح',
            titleEn: 'Morning Remembrance',
            titleBn: 'সকালের যিকর',
            textAr: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
            textEn: 'We have reached the morning and at this very time all sovereignty belongs to Allah. All praise belongs to Allah. None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise and He is over all things omnipotent.',
            textBn: 'আমরা সকালে পৌঁছেছি এবং এই সময়ে সমস্ত সার্বভৌমত্ব আল্লাহর। সমস্ত প্রশংসা আল্লাহর জন্য। আল্লাহ ছাড়া কোনো ইলাহ নেই, তিনি একক, তাঁর কোনো শরীক নেই। তাঁরই রাজত্ব এবং তাঁরই প্রশংসা, তিনি সব কিছুর ওপর সর্বশক্তিমান।',
            transliteration: 'Asbahna wa asbahal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadeer',
            reference: 'Muslim 2723',
            source: 'Hadith',
            occasion: 'Every morning',
          ),
          Dua(
            id: 'evening_remembrance',
            type: 'daily',
            titleAr: 'أذكار المساء',
            titleEn: 'Evening Remembrance',
            titleBn: 'সন্ধ্যার যিকর',
            textAr: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
            textEn: 'We have reached the evening and at this very time all sovereignty belongs to Allah. All praise belongs to Allah. None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise and He is over all things omnipotent.',
            textBn: 'আমরা সন্ধ্যায় পৌঁছেছি এবং এই সময়ে সমস্ত সার্বভৌমত্ব আল্লাহর। সমস্ত প্রশংসা আল্লাহর জন্য। আল্লাহ ছাড়া কোনো ইলাহ নেই, তিনি একক, তাঁর কোনো শরীক নেই। তাঁরই রাজত্ব এবং তাঁরই প্রশংসা, তিনি সব কিছুর ওপর সর্বশক্তিমান।',
            transliteration: 'Amsayna wa amsal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadeer',
            reference: 'Muslim 2723',
            source: 'Hadith',
            occasion: 'Every evening',
          ),
          Dua(
            id: 'before_eating',
            type: 'daily',
            titleAr: 'دعاء قبل الطعام',
            titleEn: 'Before Eating',
            titleBn: 'খাওয়ার আগে',
            textAr: 'بِسْمِ اللَّهِ',
            textEn: 'In the name of Allah.',
            textBn: 'আল্লাহর নামে।',
            transliteration: 'Bismillah',
            reference: 'Abu Dawud 3767',
            source: 'Hadith',
            occasion: 'Before every meal',
          ),
          Dua(
            id: 'after_eating',
            type: 'daily',
            titleAr: 'دعاء بعد الطعام',
            titleEn: 'After Eating',
            titleBn: 'খাওয়ার পরে',
            textAr: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
            textEn: 'All praise belongs to Allah who has given me this food and provided it for me without any might or power on my part.',
            textBn: 'সমস্ত প্রশংসা আল্লাহর জন্য যিনি আমাকে এই খাবার দিয়েছেন এবং আমার কোনো শক্তি ও ক্ষমতা ছাড়াই তা দিয়েছেন।',
            transliteration: 'Alhamdu lillahil-ladhi at\'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah',
            reference: 'Tirmidhi 3458',
            source: 'Hadith',
            occasion: 'After finishing meal',
          ),
          Dua(
            id: 'before_sleep',
            type: 'daily',
            titleAr: 'دعاء قبل النوم',
            titleEn: 'Before Sleep',
            titleBn: 'ঘুমানোর আগে',
            textAr: 'بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي وَبِكَ أَرْفَعُهُ، إِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ',
            textEn: 'In Your name my Lord, I lie down and in Your name I rise, so if You should take my soul then have mercy upon it, and if You should return my soul then protect it in the manner You do so with Your righteous servants.',
            textBn: 'হে আমার রব! আপনার নামেই আমি শুয়ে পড়লাম এবং আপনার নামেই উঠব। যদি আপনি আমার আত্মা নিয়ে নেন তাহলে তার ওপর রহম করুন। আর যদি তা ফিরিয়ে দেন তাহলে যেভাবে আপনি আপনার সৎ বান্দাদের হেফাজত করেন সেভাবে তাকেও হেফাজত করুন।',
            transliteration: 'Bismika rabbi wada\'tu janbi wa bika arfa\'uh, in amsakta nafsi farhamha, wa in arsaltaha fahfazha bima tahfazu bihi \'ibadakas-salihin',
            reference: 'Bukhari 6320',
            source: 'Hadith',
            occasion: 'Before sleeping',
          ),
          Dua(
            id: 'waking_up',
            type: 'daily',
            titleAr: 'دعاء الاستيقاظ من النوم',
            titleEn: 'Upon Waking Up',
            titleBn: 'ঘুম থেকে জাগার পর',
            textAr: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
            textEn: 'All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.',
            textBn: 'সমস্ত প্রশংসা আল্লাহর জন্য যিনি আমাদের মৃত্যু দেওয়ার পর পুনরায় জীবন দিয়েছেন এবং তাঁর কাছেই পুনরুত্থান।',
            transliteration: 'Alhamdu lillahil-ladhi ahyana ba\'da ma amatana wa ilayhin-nushur',
            reference: 'Bukhari 6312',
            source: 'Hadith',
            occasion: 'Upon waking from sleep',
          ),
          Dua(
            id: 'entering_home',
            type: 'daily',
            titleAr: 'دعاء دخول المنزل',
            titleEn: 'Entering Home',
            titleBn: 'ঘরে প্রবেশের দোয়া',
            textAr: 'بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا',
            textEn: 'In the name of Allah we enter, in the name of Allah we leave, and upon Allah our Lord we depend.',
            textBn: 'আল্লাহর নামে আমরা প্রবেশ করলাম, আল্লাহর নামে আমরা বের হলাম এবং আমাদের রব আল্লাহর উপরই আমরা ভরসা করলাম।',
            transliteration: 'Bismillahi walajna, wa bismillahi kharajna, wa \'alallahi rabbina tawakkalna',
            reference: 'Abu Dawud 5096',
            source: 'Hadith',
            occasion: 'When entering home',
          ),
          Dua(
            id: 'entering_bathroom',
            type: 'daily',
            titleAr: 'دعاء دخول الخلاء',
            titleEn: 'Entering Bathroom',
            titleBn: 'টয়লেটে প্রবেশের দোয়া',
            textAr: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
            textEn: 'O Allah, I seek protection in You from the male and female devils.',
            textBn: 'হে আল্লাহ! আমি পুরুষ ও নারী শয়তান থেকে আপনার কাছে আশ্রয় চাই।',
            transliteration: 'Allahumma inni a\'udhu bika minal-khubuthi wal-khaba\'ith',
            reference: 'Bukhari 142',
            source: 'Hadith',
            occasion: 'Before entering bathroom',
          ),
          Dua(
            id: 'leaving_bathroom',
            type: 'daily',
            titleAr: 'دعاء الخروج من الخلاء',
            titleEn: 'Leaving Bathroom',
            titleBn: 'টয়লেট থেকে বের হওয়ার দোয়া',
            textAr: 'غُفْرَانَكَ',
            textEn: 'I seek Your forgiveness.',
            textBn: 'আপনার ক্ষমা চাই।',
            transliteration: 'Ghufranaka',
            reference: 'Tirmidhi 7',
            source: 'Hadith',
            occasion: 'After leaving bathroom',
          ),
          Dua(
            id: 'when_rain',
            type: 'daily',
            titleAr: 'دعاء نزول المطر',
            titleEn: 'When It Rains',
            titleBn: 'বৃষ্টি হলে',
            textAr: 'اللَّهُمَّ صَيِّبًا نَافِعًا',
            textEn: 'O Allah, (bring) beneficial rain.',
            textBn: 'হে আল্লাহ! উপকারী বৃষ্টি দিন।',
            transliteration: 'Allahumma sayyiban nafi\'a',
            reference: 'Bukhari 1032',
            source: 'Hadith',
            occasion: 'When it rains',
          ),
        ],
      ),

      // 2. Prayer Duas
      DuaCategory(
        id: 'prayer_duas',
        nameAr: 'أدعية الصلاة',
        nameEn: 'Prayer Duas',
        nameBn: 'নামাযের দোয়া',
        descriptionAr: 'الأدعية المتعلقة بالصلاة والوضوء',
        descriptionEn: 'Duas related to prayer and ablution',
        descriptionBn: 'নামায ও অযুর সাথে সম্পর্কিত দোয়া',
        iconPath: '🕌',
        duas: [
          Dua(
            id: 'adhan_response',
            type: 'important',
            titleAr: 'إجابة الأذان',
            titleEn: 'Response to Adhan',
            titleBn: 'আযানের জবাব',
            textAr: 'اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ',
            textEn: 'O Allah, Owner of this perfect call and Owner of this prayer to be performed, grant Muhammad al-waseelah and al-fadeelah and send him upon a praised platform which You have promised him.',
            textBn: 'হে আল্লাহ! এই পূর্ণ আহ্বান ও প্রতিষ্ঠিত সালাতের রব! মুহাম্মাদকে ওসীলা ও ফযীলত দান করুন এবং তাঁকে প্রশংসিত স্থানে পৌঁছান যার ওয়াদা আপনি তাঁর সাথে করেছেন।',
            transliteration: 'Allahumma rabba hadhihid-da\'watit-tammati was-salatil-qa\'imati, aati Muhammadanil-waseelata wal-fadeelata, wab\'athhu maqaman mahmudanil-ladhi wa\'adtah',
            reference: 'Bukhari 614',
            source: 'Hadith',
            occasion: 'After hearing Adhan',
          ),
          Dua(
            id: 'before_wudu',
            type: 'important',
            titleAr: 'دعاء قبل الوضوء',
            titleEn: 'Before Ablution',
            titleBn: 'অযুর আগে',
            textAr: 'بِسْمِ اللَّهِ',
            textEn: 'In the name of Allah.',
            textBn: 'আল্লাহর নামে।',
            transliteration: 'Bismillah',
            reference: 'Abu Dawud 101',
            source: 'Hadith',
            occasion: 'Before starting ablution',
          ),
          Dua(
            id: 'after_wudu',
            type: 'important',
            titleAr: 'دعاء بعد الوضوء',
            titleEn: 'After Ablution',
            titleBn: 'অযুর পরে',
            textAr: 'أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
            textEn: 'I bear witness that none has the right to be worshipped except Allah, alone without partner, and I bear witness that Muhammad is His slave and Messenger.',
            textBn: 'আমি সাক্ষ্য দিচ্ছি যে, আল্লাহ ছাড়া কোনো ইলাহ নেই, তিনি একক, তাঁর কোনো শরীক নেই। আর আমি সাক্ষ্য দিচ্ছি যে, মুহাম্মাদ তাঁর বান্দা ও রাসূল।',
            transliteration: 'Ashhadu an la ilaha illallahu wahdahu la sharika lah, wa ashhadu anna Muhammadan \'abduhu wa rasuluh',
            reference: 'Muslim 234',
            source: 'Hadith',
            occasion: 'After completing ablution',
          ),
          Dua(
            id: 'entering_mosque',
            type: 'important',
            titleAr: 'دعاء دخول المسجد',
            titleEn: 'Entering Mosque',
            titleBn: 'মসজিদে প্রবেশের দোয়া',
            textAr: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
            textEn: 'O Allah, open for me the doors of Your mercy.',
            textBn: 'হে আল্লাহ! আমার জন্য আপনার রহমতের দরজা খুলে দিন।',
            transliteration: 'Allahumma-ftah li abwaba rahmatik',
            reference: 'Muslim 713',
            source: 'Hadith',
            occasion: 'When entering mosque',
          ),
          Dua(
            id: 'leaving_mosque',
            type: 'important',
            titleAr: 'دعاء الخروج من المسجد',
            titleEn: 'Leaving Mosque',
            titleBn: 'মসজিদ থেকে বের হওয়ার দোয়া',
            textAr: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
            textEn: 'O Allah, I ask You from Your bounty.',
            textBn: 'হে আল্লাহ! আমি আপনার অনুগ্রহ চাই।',
            transliteration: 'Allahumma inni as\'aluka min fadlik',
            reference: 'Muslim 713',
            source: 'Hadith',
            occasion: 'When leaving mosque',
          ),
          Dua(
            id: 'between_sujood',
            type: 'important',
            titleAr: 'دعاء بين السجدتين',
            titleEn: 'Between Two Prostrations',
            titleBn: 'দুই সিজদার মাঝখানে',
            textAr: 'رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي',
            textEn: 'My Lord, forgive me. My Lord, forgive me.',
            textBn: 'হে আমার রব! আমাকে ক্ষমা করুন। হে আমার রব! আমাকে ক্ষমা করুন।',
            transliteration: 'Rabbi-ghfir li, rabbi-ghfir li',
            reference: 'Ibn Majah 898',
            source: 'Hadith',
            occasion: 'Between two prostrations in prayer',
          ),
          Dua(
            id: 'in_sujood',
            type: 'important',
            titleAr: 'دعاء السجود',
            titleEn: 'During Prostration',
            titleBn: 'সিজদায়',
            textAr: 'سُبْحَانَ رَبِّيَ الْأَعْلَى',
            textEn: 'How Perfect is my Lord, the Most High.',
            textBn: 'আমার রব মহাপবিত্র, যিনি সর্বোচ্চ।',
            transliteration: 'Subhana rabbiyal-a\'la',
            reference: 'Muslim 772',
            source: 'Hadith',
            occasion: 'During prostration (3 times minimum)',
          ),
          Dua(
            id: 'in_ruku',
            type: 'important',
            titleAr: 'دعاء الركوع',
            titleEn: 'During Bowing (Ruku)',
            titleBn: 'রুকুতে',
            textAr: 'سُبْحَانَ رَبِّيَ الْعَظِيمِ',
            textEn: 'How Perfect is my Lord, the Supreme.',
            textBn: 'আমার রব মহাপবিত্র, যিনি মহান।',
            transliteration: 'Subhana rabbiyal-\'azim',
            reference: 'Muslim 772',
            source: 'Hadith',
            occasion: 'During bowing in prayer (3 times minimum)',
          ),
        ],
      ),

      // 3. Travel Duas
      DuaCategory(
        id: 'travel_duas',
        nameAr: 'أدعية السفر',
        nameEn: 'Travel Duas',
        nameBn: 'সফরের দোয়া',
        descriptionAr: 'أدعية السفر والانتقال',
        descriptionEn: 'Duas for traveling and journeys',
        descriptionBn: 'ভ্রমণ ও যাত্রার দোয়া',
        iconPath: '🧳',
        duas: [
          Dua(
            id: 'leaving_home',
            type: 'important',
            titleAr: 'دعاء الخروج من المنزل',
            titleEn: 'Leaving Home',
            titleBn: 'ঘর থেকে বের হওয়ার দোয়া',
            textAr: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
            textEn: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
            textBn: 'আল্লাহর নামে, আমি আল্লাহর ওপর ভরসা করলাম, আল্লাহ ছাড়া কোনো শক্তি ও ক্ষমতা নেই।',
            transliteration: 'Bismillah, tawakkaltu \'alallah, wa la hawla wa la quwwata illa billah',
            reference: 'Abu Dawud 5095',
            source: 'Hadith',
            occasion: 'When leaving home',
          ),
          Dua(
            id: 'entering_vehicle',
            type: 'important',
            titleAr: 'دعاء ركوب الدابة',
            titleEn: 'Entering Vehicle',
            titleBn: 'যানবাহনে চড়ার দোয়া',
            textAr: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ ○ وَإِنَّا إِلَى رَبِّنَا لَمُنقَلِبُونَ',
            textEn: 'How perfect He is, the One who has placed this (transport) at our service, and we ourselves would not have been capable of that, and to our Lord is our final destiny.',
            textBn: 'পবিত্র তিনি যিনি এটাকে (যানবাহনকে) আমাদের অধীনস্থ করেছেন, অথচ আমরা এর উপযুক্ত ছিলাম না। আর নিশ্চয়ই আমরা আমাদের রবের নিকট প্রত্যাবর্তনকারী।',
            transliteration: 'Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun',
            reference: 'Az-Zukhruf 43:13-14',
            source: 'Quran',
            occasion: 'When entering any vehicle',
          ),
          Dua(
            id: 'travel_journey',
            type: 'important',
            titleAr: 'دعاء السفر',
            titleEn: 'Setting Out on a Journey',
            titleBn: 'সফর শুরুর দোয়া',
            textAr: 'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى وَمِنَ الْعَمَلِ مَا تَرْضَى',
            textEn: 'O Allah, we ask You on this our journey for goodness and piety, and for works that are pleasing to You.',
            textBn: 'হে আল্লাহ! আমরা এই সফরে আপনার কাছে কল্যাণ ও তাকওয়া চাই এবং এমন আমল চাই যা আপনি পছন্দ করেন।',
            transliteration: 'Allahumma inna nas\'aluka fi safarina hadhal-birra wat-taqwa, wa minal-\'amali ma tarda',
            reference: 'Muslim 1342',
            source: 'Hadith',
            occasion: 'When starting a journey',
          ),
          Dua(
            id: 'returning_journey',
            type: 'important',
            titleAr: 'دعاء الرجوع من السفر',
            titleEn: 'Returning from Journey',
            titleBn: 'সফর থেকে ফেরার দোয়া',
            textAr: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ',
            textEn: 'We return, repentant, worshipping, prostrating and praising our Lord.',
            textBn: 'আমরা ফিরে আসছি, তওবাকারী, ইবাদতকারী, আমাদের রবের প্রশংসাকারী।',
            transliteration: 'Ayibuna ta\'ibuna \'abiduna li-rabbina hamidun',
            reference: 'Bukhari 1797',
            source: 'Hadith',
            occasion: 'When returning from travel',
          ),
        ],
      ),

      // 4. Protection Duas
      DuaCategory(
        id: 'protection_duas',
        nameAr: 'أدعية الحماية',
        nameEn: 'Protection Duas',
        nameBn: 'সুরক্ষার দোয়া',
        descriptionAr: 'أدعية الحفظ والحماية من الشرور',
        descriptionEn: 'Duas for protection from evil and harm',
        descriptionBn: 'মন্দ ও ক্ষতি থেকে সুরক্ষার দোয়া',
        iconPath: '🛡️',
        duas: [
          Dua(
            id: 'ayat_kursi',
            type: 'important',
            titleAr: 'آية الكرسي',
            titleEn: 'Ayat al-Kursi',
            titleBn: 'আয়াতুল কুরসী',
            textAr: 'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ',
            textEn: 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.',
            textBn: 'আল্লাহ, তিনি ছাড়া কোনো ইলাহ নেই। তিনি চিরঞ্জীব, সবকিছুর ধারক। তাঁকে তন্দ্রা ও নিদ্রা স্পর্শ করে না। আসমান ও জমিনে যা কিছু রয়েছে, সব তাঁরই। কে আছে এমন, যে সুপারিশ করবে তাঁর কাছে তাঁর অনুমতি ছাড়া? তিনি জানেন তাদের সামনে ও পেছনে যা কিছু রয়েছে। আর তাঁর জ্ঞানের কিছুই তারা আয়ত্ত করতে পারে না, তবে যতটুকু তিনি চান। তাঁর কুরসী আসমান ও জমিন পরিবেষ্টন করে আছে। আর সেগুলোর রক্ষণাবেক্ষণ তাঁর জন্য কঠিন নয়। তিনি সর্বোচ্চ, মহান।',
            transliteration: 'Allahu la ilaha illa huwal-hayyul-qayyum, la ta\'khudhahu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ard, man dhal-ladhi yashfa\'u \'indahu illa bi-idhnih, ya\'lamu ma bayna aydihim wa ma khalfahum, wa la yuhituna bi shay\'in min \'ilmihi illa bima sha\'a, wasi\'a kursiyyuhus-samawati wal-arda, wa la ya\'uduhu hifdhuhuma, wa huwal-\'aliyyul-\'adhim',
            reference: 'Al-Baqarah 2:255',
            source: 'Quran',
            occasion: 'Morning, evening, after prayers',
          ),
          Dua(
            id: 'three_quls',
            type: 'important',
            titleAr: 'المعوذات الثلاث',
            titleEn: 'Three Quls (Surat al-Ikhlas, al-Falaq, an-Nas)',
            titleBn: 'তিন কুল (সূরা ইখলাস, ফালাক, নাস)',
            textAr: 'قُلْ هُوَ اللَّهُ أَحَدٌ ○ اللَّهُ الصَّمَدُ ○ لَمْ يَلِدْ وَلَمْ يُولَدْ ○ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
            textEn: 'Say, "He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, Nor is there to Him any equivalent."',
            textBn: 'বলুন, তিনি আল্লাহ, এক। আল্লাহ অমুখাপেক্ষী। তিনি কাউকে জন্ম দেননি এবং কেউ তাঁকে জন্ম দেয়নি। আর তাঁর সমতুল্য কেউ নেই।',
            transliteration: 'Qul huwallahu ahad, Allahus-samad, lam yalid wa lam yulad, wa lam yakun lahu kufuwan ahad',
            reference: 'Al-Ikhlas 112:1-4',
            source: 'Quran',
            occasion: 'Morning, evening, after prayers (3 times)',
          ),
          Dua(
            id: 'evil_eye_protection',
            type: 'important',
            titleAr: 'دعاء الحسد والعين',
            titleEn: 'Protection from Evil Eye',
            titleBn: 'বদনজর থেকে সুরক্ষা',
            textAr: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
            textEn: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
            textBn: 'আমি আল্লাহর পরিপূর্ণ বাণীসমূহের মাধ্যমে তাঁর সৃষ্টির অনিষ্ট থেকে আশ্রয় চাই।',
            transliteration: 'A\'udhu bi kalimatillahit-tammati min sharri ma khalaq',
            reference: 'Muslim 2708',
            source: 'Hadith',
            occasion: 'Morning and evening, before sleep',
          ),
          Dua(
            id: 'protection_shaytan',
            type: 'important',
            titleAr: 'دعاء من الشيطان',
            titleEn: 'Protection from Satan',
            titleBn: 'শয়তান থেকে সুরক্ষা',
            textAr: 'أَعُوذُ بِاللَّهِ السَّمِيعِ الْعَلِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
            textEn: 'I seek refuge with Allah, the All-Hearing, the All-Knowing, from the accursed Satan.',
            textBn: 'আমি সর্বশ্রোতা, সর্বজ্ঞ আল্লাহর কাছে বিতাড়িত শয়তান থেকে আশ্রয় চাই।',
            transliteration: 'A\'udhu billahis-sami\'il-\'alimi minash-shaytanir-rajim',
            reference: 'Abu Dawud 1527',
            source: 'Hadith',
            occasion: 'Before Quran recitation, when angry',
          ),
          Dua(
            id: 'four_quls',
            type: 'important',
            titleAr: 'الأربع القل',
            titleEn: 'The Four Quls',
            titleBn: 'চার কুল',
            textAr: 'قُلْ يَا أَيُّهَا الْكَافِرُونَ ○ لَا أَعْبُدُ مَا تَعْبُدُونَ',
            textEn: 'Say, "O disbelievers, I do not worship what you worship."',
            textBn: 'বলুন, হে কাফেররা! আমি তার ইবাদত করি না যার ইবাদত তোমরা কর।',
            transliteration: 'Qul ya ayyuhal-kafirun, la a\'budu ma ta\'budun',
            reference: 'Al-Kafirun 109:1-2',
            source: 'Quran',
            occasion: 'Before sleep for protection',
          ),
        ],
      ),

      // 5. Important Duas from Quran
      DuaCategory(
        id: 'quranic_duas',
        nameAr: 'الأدعية القرآنية',
        nameEn: 'Quranic Duas',
        nameBn: 'কুরআনিক দোয়া',
        descriptionAr: 'الأدعية المأثورة من القرآن الكريم',
        descriptionEn: 'Important duas mentioned in the Holy Quran',
        descriptionBn: 'পবিত্র কুরআনে উল্লেখিত গুরুত্বপূর্ণ দোয়া',
        iconPath: '📖',
        duas: [
          Dua(
            id: 'rabbana_atina',
            type: 'important',
            titleAr: 'ربنا آتنا في الدنيا حسنة',
            titleEn: 'Our Lord, give us good in this world',
            titleBn: 'হে আমাদের রব, আমাদের দুনিয়ায় কল্যাণ দিন',
            textAr: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
            textEn: 'Our Lord, give us good in this world and good in the next world and save us from the punishment of the Fire.',
            textBn: 'হে আমাদের রব! আমাদের দুনিয়াতে কল্যাণ দিন, আখিরাতেও কল্যাণ দিন এবং আগুনের আযাব থেকে রক্ষা করুন।',
            transliteration: 'Rabbana atina fi\'d-dunya hasanatan wa fi\'l-akhirati hasanatan wa qina \'adhab an-nar',
            reference: 'Al-Baqarah 2:201',
            source: 'Quran',
            occasion: 'Anytime - comprehensive dua',
          ),
          Dua(
            id: 'rabbana_la_tuzigh',
            type: 'important',
            titleAr: 'ربنا لا تزغ قلوبنا',
            titleEn: 'Our Lord, do not let our hearts deviate',
            titleBn: 'হে আমাদের রব, আমাদের হৃদয়কে বক্র করবেন না',
            textAr: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً إِنَّكَ أَنتَ الْوَهَّابُ',
            textEn: 'Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.',
            textBn: 'হে আমাদের রব! আপনি আমাদের হিদায়াত দেওয়ার পর আমাদের হৃদয়কে সত্য পথ থেকে সরিয়ে দেবেন না এবং আপনার পক্ষ থেকে আমাদের রহমত দান করুন। নিশ্চয়ই আপনি মহাদাতা।',
            transliteration: 'Rabbana la tuzigh qulubana ba\'da idh hadaytana wa hab lana min ladunka rahmatan innaka antal-wahhab',
            reference: 'Ali \'Imran 3:8',
            source: 'Quran',
            occasion: 'For steadfastness in faith',
          ),
          Dua(
            id: 'rabbana_taqabbal',
            type: 'important',
            titleAr: 'ربنا تقبل منا',
            titleEn: 'Our Lord, accept from us',
            titleBn: 'হে আমাদের রব, আমাদের থেকে কবুল করুন',
            textAr: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ',
            textEn: 'Our Lord, accept this from us. Indeed, You are the Hearing, the Knowing.',
            textBn: 'হে আমাদের রব! আমাদের থেকে কবুল করুন। নিশ্চয়ই আপনি সর্বশ্রোতা, সর্বজ্ঞানী।',
            transliteration: 'Rabbana taqabbal minna innaka antas-sami\'ul-\'alim',
            reference: 'Al-Baqarah 2:127',
            source: 'Quran',
            occasion: 'After good deeds and worship',
          ),
          Dua(
            id: 'rabbana_afrigh',
            type: 'important',
            titleAr: 'ربنا أفرغ علينا صبرا',
            titleEn: 'Our Lord, pour upon us patience',
            titleBn: 'হে আমাদের রব, আমাদের ধৈর্য দান করুন',
            textAr: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
            textEn: 'Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.',
            textBn: 'হে আমাদের রব! আমাদের ধৈর্য দান করুন, আমাদের পা দৃঢ় রাখুন এবং কাফের সম্প্রদায়ের বিরুদ্ধে আমাদের সাহায্য করুন।',
            transliteration: 'Rabbana afrigh \'alayna sabran wa thabbit aqdamana wansurna \'alal-qawmil-kafirin',
            reference: 'Al-Baqarah 2:250',
            source: 'Quran',
            occasion: 'In times of hardship and trials',
          ),
          Dua(
            id: 'rabbana_la_tuakhidhna',
            type: 'important',
            titleAr: 'ربنا لا تؤاخذنا',
            titleEn: 'Our Lord, do not impose blame',
            titleBn: 'হে আমাদের রব, আমাদের পাকড়াও করবেন না',
            textAr: 'رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا',
            textEn: 'Our Lord, do not impose blame upon us if we have forgotten or erred.',
            textBn: 'হে আমাদের রব! আমরা ভুলে গেলে বা ভুল করলে আমাদের পাকড়াও করবেন না।',
            transliteration: 'Rabbana la tu\'akhidhna in nasina aw akhta\'na',
            reference: 'Al-Baqarah 2:286',
            source: 'Quran',
            occasion: 'Seeking forgiveness for mistakes',
          ),
          Dua(
            id: 'rabbana_wa_la_tahmil',
            type: 'important',
            titleAr: 'ربنا ولا تحمل علينا',
            titleEn: 'Our Lord, do not place burden',
            titleBn: 'হে আমাদের রব, আমাদের উপর বোঝা চাপাবেন না',
            textAr: 'رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا',
            textEn: 'Our Lord, and lay not upon us a burden like that which You laid upon those before us.',
            textBn: 'হে আমাদের রব! আমাদের পূর্ববর্তীদের উপর যেমন বোঝা চাপিয়ে দিয়েছিলেন, আমাদের উপর সেরকম বোঝা চাপাবেন না।',
            transliteration: 'Rabbana wa la tahmil \'alayna isran kama hamaltahu \'alal-ladhina min qablina',
            reference: 'Al-Baqarah 2:286',
            source: 'Quran',
            occasion: 'Seeking ease in matters',
          ),
          Dua(
            id: 'rabbana_innana_amanna',
            type: 'important',
            titleAr: 'ربنا إننا آمنا',
            titleEn: 'Our Lord, indeed we have believed',
            titleBn: 'হে আমাদের রব, আমরা ঈমান এনেছি',
            textAr: 'رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ',
            textEn: 'Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire.',
            textBn: 'হে আমাদের রব! আমরা ঈমান এনেছি, সুতরাং আমাদের গুনাহ ক্ষমা করুন এবং আমাদের জাহান্নামের আযাব থেকে রক্ষা করুন।',
            transliteration: 'Rabbana innana amanna faghfir lana dhunubana wa qina \'adhaban-nar',
            reference: 'Ali \'Imran 3:16',
            source: 'Quran',
            occasion: 'After declaring faith',
          ),
        ],
      ),

      // 6. Forgiveness Duas
      DuaCategory(
        id: 'forgiveness_duas',
        nameAr: 'أدعية الاستغفار',
        nameEn: 'Forgiveness Duas',
        nameBn: 'ক্ষমার দোয়া',
        descriptionAr: 'أدعية طلب المغفرة والتوبة',
        descriptionEn: 'Duas for seeking forgiveness and repentance',
        descriptionBn: 'ক্ষমা প্রার্থনা ও তওবার দোয়া',
        iconPath: '🤲',
        duas: [
          Dua(
            id: 'sayyidul_istighfar',
            type: 'important',
            titleAr: 'سيد الاستغفار',
            titleEn: 'Master of Seeking Forgiveness',
            titleBn: 'সাইয়্যিদুল ইস্তিগফার',
            textAr: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
            textEn: 'O Allah, You are my Lord, none has the right to be worshipped except You, You created me and I am Your servant and I abide to Your covenant and promise as best I can, I seek refuge in You from the evil of which I committed. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for verily none can forgive sin except You.',
            textBn: 'হে আল্লাহ! আপনি আমার রব, আপনি ছাড়া কোনো ইলাহ নেই। আপনি আমাকে সৃষ্টি করেছেন এবং আমি আপনার বান্দা। আমি যথাসাধ্য আপনার অঙ্গীকার ও প্রতিশ্রুতির ওপর আছি। আমি যা করেছি তার অনিষ্ট থেকে আপনার কাছে আশ্রয় চাই। আপনার নিয়ামতের কথা স্বীকার করছি এবং আমার গুনাহ স্বীকার করছি। অতএব আমাকে ক্ষমা করুন, কারণ আপনি ছাড়া কেউ গুনাহ ক্ষমা করতে পারে না।',
            transliteration: 'Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana \'abduk, wa ana \'ala \'ahdika wa wa\'dika mastata\'t, a\'udhu bika min sharri ma sana\'t, abu\'u laka bi ni\'matika \'alayya wa abu\'u bi dhanbi faghfir li fa\'innahu la yaghfiru\'dh-dhunuba illa ant',
            reference: 'Bukhari 6306',
            source: 'Hadith',
            occasion: 'Morning and evening',
          ),
          Dua(
            id: 'simple_istighfar',
            type: 'daily',
            titleAr: 'الاستغفار البسيط',
            titleEn: 'Simple Istighfar',
            titleBn: 'সাধারণ ইস্তিগফার',
            textAr: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيَّ الْقَيُّومَ وَأَتُوبُ إِلَيْهِ',
            textEn: 'I seek forgiveness of Allah the Magnificent, whom there is none worthy of worship except Him, the Living, the Eternal, and I repent unto Him.',
            textBn: 'আমি মহান আল্লাহর কাছে ক্ষমা প্রার্থনা করি, যিনি ছাড়া কোনো ইলাহ নেই, যিনি চিরঞ্জীব, চিরস্থায়ী, এবং তাঁর কাছে তওবা করি।',
            transliteration: 'Astaghfirullaha\'l-\'azim alladhi la ilaha illa huwa\'l-hayya\'l-qayyuma wa atubu ilayh',
            reference: 'Abu Dawud 1517',
            source: 'Hadith',
            occasion: 'Anytime (100 times daily recommended)',
          ),
          Dua(
            id: 'repentance',
            type: 'important',
            titleAr: 'دعاء التوبة',
            titleEn: 'Seeking Repentance',
            titleBn: 'তওবার দোয়া',
            textAr: 'رَبِّ إِنِّي ظَلَمْتُ نَفْسِي وَأَعْتَرِفُ بِذَنْبِي فَاغْفِرْ لِي',
            textEn: 'My Lord, I have indeed wronged my soul, so forgive me.',
            textBn: 'হে আমার রব! আমি আমার আত্মার প্রতি জুলুম করেছি, আমাকে ক্ষমা করুন।',
            transliteration: 'Rabbi inni zalamtu nafsi fa-ghfir li',
            reference: 'Al-Qasas 28:16',
            source: 'Quran',
            occasion: 'When seeking sincere repentance',
          ),
          Dua(
            id: 'constant_forgiveness',
            type: 'daily',
            titleAr: 'الاستغفار المستمر',
            titleEn: 'Constant Seeking of Forgiveness',
            titleBn: 'নিয়মিত ক্ষমা প্রার্থনা',
            textAr: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنتَ خَيْرُ الرَّاحِمِينَ',
            textEn: 'My Lord, forgive and have mercy, and You are the best of the merciful.',
            textBn: 'হে আমার রব! ক্ষমা করুন ও দয়া করুন, আপনি সর্বশ্রেষ্ঠ দয়াবান।',
            transliteration: 'Rabbighfir warham wa anta khayru\'r-rahimin',
            reference: 'Al-Mu\'minun 23:118',
            source: 'Quran',
            occasion: 'Daily for continuous forgiveness',
          ),
        ],
      ),

      // 7. Special Occasion Duas
      DuaCategory(
        id: 'occasion_duas',
        nameAr: 'أدعية المناسبات',
        nameEn: 'Occasion Duas',
        nameBn: 'বিশেষ উপলক্ষের দোয়া',
        descriptionAr: 'أدعية للمناسبات الخاصة والأعياد',
        descriptionEn: 'Duas for special occasions and celebrations',
        descriptionBn: 'বিশেষ অনুষ্ঠান ও উৎসবের দোয়া',
        iconPath: '🎊',
        duas: [
          Dua(
            id: 'new_month',
            type: 'occasion',
            titleAr: 'دعاء رؤية الهلال',
            titleEn: 'Seeing the New Moon',
            titleBn: 'নতুন চাঁদ দেখার দোয়া',
            textAr: 'اللَّهُمَّ أَهِلَّهُ عَلَيْنَا بِالْأَمْنِ وَالْإِيمَانِ وَالسَّلَامَةِ وَالْإِسْلَامِ رَبِّي وَرَبُّكَ اللَّهُ',
            textEn: 'O Allah, let this month pass over us with security, faith, safety, and Islam. My Lord and your Lord is Allah.',
            textBn: 'হে আল্লাহ! এই মাসটি আমাদের উপর নিরাপত্তা, ঈমান, শান্তি ও ইসলামের সাথে অতিক্রম করুন। আমার ও তোমার রব আল্লাহ।',
            transliteration: 'Allahumma ahillahu \'alayna bil-amni wal-iman, was-salamati wal-islam, rabbi wa rabbuka Allah',
            reference: 'Tirmidhi 3451',
            source: 'Hadith',
            occasion: 'When seeing the new moon',
          ),
          Dua(
            id: 'friday',
            type: 'occasion',
            titleAr: 'دعاء يوم الجمعة',
            titleEn: 'Friday Special Dua',
            titleBn: 'জুমার দিনের বিশেষ দোয়া',
            textAr: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
            textEn: 'O Allah, send prayers and peace upon our Prophet Muhammad.',
            textBn: 'হে আল্লাহ! আমাদের নবী মুহাম্মাদের উপর সালাত ও সালাম পাঠান।',
            transliteration: 'Allahumma salli wa sallim \'ala nabiyyina Muhammad',
            reference: 'Abu Dawud 1047',
            source: 'Hadith',
            occasion: 'Frequently on Friday',
          ),
          Dua(
            id: 'after_rain',
            type: 'occasion',
            titleAr: 'دعاء بعد نزول المطر',
            titleEn: 'After Rain',
            titleBn: 'বৃষ্টির পরে',
            textAr: 'مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ',
            textEn: 'We have received rain by the grace and mercy of Allah.',
            textBn: 'আল্লাহর অনুগ্রহ ও রহমতে আমরা বৃষ্টি পেয়েছি।',
            transliteration: 'Muturna bi-fadlillahi wa rahmatihi',
            reference: 'Bukhari 846',
            source: 'Hadith',
            occasion: 'After rainfall',
          ),
          Dua(
            id: 'breaking_fast',
            type: 'occasion',
            titleAr: 'دعاء الإفطار',
            titleEn: 'Breaking Fast (Iftar)',
            titleBn: 'ইফতারের দোয়া',
            textAr: 'اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ',
            textEn: 'O Allah, for You I have fasted and with Your provision I have broken my fast.',
            textBn: 'হে আল্লাহ! আপনার জন্য রোজা রেখেছি এবং আপনার দেওয়া রিজিক দিয়ে ইফতার করছি।',
            transliteration: 'Allahumma laka sumtu wa \'ala rizqika aftartu',
            reference: 'Abu Dawud 2358',
            source: 'Hadith',
            occasion: 'When breaking fast',
          ),
          Dua(
            id: 'laylatul_qadr',
            type: 'occasion',
            titleAr: 'دعاء ليلة القدر',
            titleEn: 'Laylatul Qadr (Night of Power)',
            titleBn: 'লাইলাতুল কদরের দোয়া',
            textAr: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
            textEn: 'O Allah, You are Most Forgiving, and You love forgiveness; so forgive me.',
            textBn: 'হে আল্লাহ! আপনি ক্ষমাশীল, ক্ষমা পছন্দ করেন, তাই আমাকে ক্ষমা করুন।',
            transliteration: 'Allahumma innaka \'afuwwun tuhibbul-\'afwa fa\'fu \'anni',
            reference: 'Tirmidhi 3513',
            source: 'Hadith',
            occasion: 'On Laylatul Qadr in Ramadan',
          ),
          Dua(
            id: 'visiting_grave',
            type: 'occasion',
            titleAr: 'دعاء زيارة القبور',
            titleEn: 'Visiting Graves',
            titleBn: 'কবর জিয়ারতের দোয়া',
            textAr: 'السَّلَامُ عَلَيْكُمْ أَهْلَ الدِّيَارِ مِنَ الْمُؤْمِنِينَ وَالْمُسْلِمِينَ وَإِنَّا إِن شَاءَ اللَّهُ بِكُمْ لَاحِقُونَ',
            textEn: 'Peace be upon you, O inhabitants of the dwellings (i.e., the graves), from among the believers and the Muslims, and we, if Allah wills, will join you.',
            textBn: 'তোমাদের উপর শান্তি বর্ষিত হোক, হে মুমিন ও মুসলিম কবরবাসীগণ! ইনশাআল্লাহ আমরাও তোমাদের সাথে মিলিত হব।',
            transliteration: 'As-salamu \'alaykum ahla\'d-diyari mina\'l-mu\'minina wal-muslimin wa inna in sha\'allahu bikum lahiqun',
            reference: 'Muslim 975',
            source: 'Hadith',
            occasion: 'When visiting cemetery',
          ),
        ],
      ),

      // 8. Health & Recovery Duas
      DuaCategory(
        id: 'health_duas',
        nameAr: 'أدعية الصحة والشفاء',
        nameEn: 'Health & Recovery',
        nameBn: 'স্বাস্থ্য ও আরোগ্যের দোয়া',
        descriptionAr: 'أدعية للصحة والشفاء من الأمراض',
        descriptionEn: 'Duas for health and healing from illness',
        descriptionBn: 'স্বাস্থ্য ও রোগ থেকে আরোগ্যের দোয়া',
        iconPath: '💊',
        duas: [
          Dua(
            id: 'when_sick',
            type: 'important',
            titleAr: 'دعاء المريض',
            titleEn: 'When Sick',
            titleBn: 'অসুস্থ হলে',
            textAr: 'أَذْهِبِ الْبَاسَ رَبَّ النَّاسِ وَاشْفِ أَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ شِفَاءً لَا يُغَادِرُ سَقَمًا',
            textEn: 'Remove the hardship, O Lord of mankind, and heal, You are the Healer. There is no healing except Your healing, a healing that leaves no illness.',
            textBn: 'হে মানুষের রব! কষ্ট দূর করুন এবং আরোগ্য দান করুন। আপনিই আরোগ্যদাতা। আপনার আরোগ্য ছাড়া কোনো আরোগ্য নেই। এমন আরোগ্য যা কোনো রোগ ছেড়ে যায় না।',
            transliteration: 'Adhhib al-ba\'s rabba\'n-nas, washfi anta\'sh-shafi, la shifa\'a illa shifa\'uk, shifan la yughadiru saqama',
            reference: 'Bukhari 5675',
            source: 'Hadith',
            occasion: 'When someone is ill',
          ),
          Dua(
            id: 'good_health',
            type: 'daily',
            titleAr: 'دعاء العافية',
            titleEn: 'For Good Health',
            titleBn: 'সুস্বাস্থ্যের দোয়া',
            textAr: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي',
            textEn: 'O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight.',
            textBn: 'হে আল্লাহ! আমার শরীরে আফিয়ত দিন। হে আল্লাহ! আমার কানে আফিয়ত দিন। হে আল্লাহ! আমার চোখে আফিয়ত দিন।',
            transliteration: 'Allahumma \'afini fi badani, allahumma \'afini fi sam\'i, allahumma \'afini fi basari',
            reference: 'Abu Dawud 5090',
            source: 'Hadith',
            occasion: 'Daily morning',
          ),
          Dua(
            id: 'visiting_sick',
            type: 'important',
            titleAr: 'دعاء عيادة المريض',
            titleEn: 'Visiting the Sick',
            titleBn: 'রোগী দেখতে গেলে',
            textAr: 'لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ',
            textEn: 'Do not worry, it will be a purification (for you), if Allah wills.',
            textBn: 'চিন্তা নেই, ইনশাআল্লাহ এটি আপনার জন্য পবিত্রতা হবে।',
            transliteration: 'La ba\'sa, tahurun in sha\'Allah',
            reference: 'Bukhari 3616',
            source: 'Hadith',
            occasion: 'When visiting a sick person',
          ),
          Dua(
            id: 'pain_relief',
            type: 'important',
            titleAr: 'دعاء الألم',
            titleEn: 'For Pain Relief',
            titleBn: 'ব্যথার জন্য',
            textAr: 'بِسْمِ اللَّهِ (ثَلَاثًا) أَعُوذُ بِعِزَّةِ اللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ (سَبْعَ مَرَّاتٍ)',
            textEn: 'In the name of Allah (3 times). I seek refuge in Allah\'s Might and Power from the evil of what I feel and worry about (7 times).',
            textBn: 'আল্লাহর নামে (৩ বার)। আমি আল্লাহর ইজ্জত ও কুদরতের মাধ্যমে আশ্রয় চাই যা আমি অনুভব করছি ও যার ভয় পাচ্ছি তা থেকে (৭ বার)।',
            transliteration: 'Bismillah (3 times). A\'udhu bi \'izzatillahi wa qudratihi min sharri ma ajidu wa uhadhiru (7 times)',
            reference: 'Muslim 2202',
            source: 'Hadith',
            occasion: 'When feeling pain',
          ),
        ],
      ),

      // 9. Success & Guidance Duas
      DuaCategory(
        id: 'success_duas',
        nameAr: 'أدعية النجاح والهداية',
        nameEn: 'Success & Guidance',
        nameBn: 'সাফল্য ও হেদায়েতের দোয়া',
        descriptionAr: 'أدعية للنجاح في الأعمال والهداية',
        descriptionEn: 'Duas for success in endeavors and guidance',
        descriptionBn: 'কাজে সাফল্য ও সঠিক পথের দোয়া',
        iconPath: '🎯',
        duas: [
          Dua(
            id: 'istikhara',
            type: 'important',
            titleAr: 'دعاء الاستخارة',
            titleEn: 'Istikhara (Seeking Guidance)',
            titleBn: 'ইস্তিখারার দোয়া',
            textAr: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ وَتَعْلَمُ وَلَا أَعْلَمُ وَأَنْتَ عَلَّامُ الْغُيُوبِ',
            textEn: 'O Allah, I seek guidance from Your knowledge, and Power from Your Might, and I ask for Your great blessings. You are capable and I am not. You know and I do not. You are the Knower of the unseen.',
            textBn: 'হে আল্লাহ! আমি আপনার জ্ঞানের মাধ্যমে কল্যাণ কামনা করি, আপনার ক্ষমতার মাধ্যমে শক্তি প্রার্থনা করি এবং আপনার মহান অনুগ্রহ চাই। আপনি সক্ষম, আমি অক্ষম। আপনি জানেন, আমি জানি না। আপনি অদৃশ্যের জ্ঞানী।',
            transliteration: 'Allahumma inni astakhiruka bi \'ilmika wa astaqdiruka bi qudratika wa as\'aluka min fadlika\'l-\'azim, fa innaka taqdiru wa la aqdir, wa ta\'lamu wa la a\'lam, wa anta \'allamu\'l-ghuyub',
            reference: 'Bukhari 1166',
            source: 'Hadith',
            occasion: 'Before making important decisions',
          ),
          Dua(
            id: 'before_exam',
            type: 'occasion',
            titleAr: 'دعاء قبل الامتحان',
            titleEn: 'Before Exam/Test',
            titleBn: 'পরীক্ষার আগে',
            textAr: 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا',
            textEn: 'O Allah, there is nothing easy except what You make easy, and You make the difficult easy if it be Your Will.',
            textBn: 'হে আল্লাহ! আপনি যা সহজ করেন তা ছাড়া কিছুই সহজ নয়। আর আপনি ইচ্ছা করলে কঠিনকেও সহজ করে দেন।',
            transliteration: 'Allahumma la sahla illa ma ja\'altahu sahla, wa anta taj\'alul-hazna idha shi\'ta sahla',
            reference: 'Ibn Hibban 2427',
            source: 'Hadith',
            occasion: 'Before exams or difficult tasks',
          ),
          Dua(
            id: 'seeking_knowledge',
            type: 'important',
            titleAr: 'دعاء طلب العلم',
            titleEn: 'Seeking Knowledge',
            titleBn: 'জ্ঞান অর্জনের দোয়া',
            textAr: 'رَبِّ زِدْنِي عِلْمًا',
            textEn: 'My Lord, increase me in knowledge.',
            textBn: 'হে আমার রব! আমার জ্ঞান বাড়িয়ে দিন।',
            transliteration: 'Rabbi zidni \'ilma',
            reference: 'Ta-Ha 20:114',
            source: 'Quran',
            occasion: 'When seeking knowledge and learning',
          ),
          Dua(
            id: 'beneficial_knowledge',
            type: 'important',
            titleAr: 'دعاء العلم النافع',
            titleEn: 'For Beneficial Knowledge',
            titleBn: 'উপকারী জ্ঞানের জন্য',
            textAr: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا',
            textEn: 'O Allah, I ask You for beneficial knowledge, goodly provision, and acceptable deeds.',
            textBn: 'হে আল্লাহ! আমি আপনার কাছে উপকারী জ্ঞান, পবিত্র রিজিক এবং কবুলযোগ্য আমল প্রার্থনা করি।',
            transliteration: 'Allahumma inni as\'aluka \'ilman nafi\'a, wa rizqan tayyiba, wa \'amalan mutaqabbala',
            reference: 'Ibn Majah 925',
            source: 'Hadith',
            occasion: 'Daily morning prayer',
          ),
          Dua(
            id: 'righteous_deeds',
            type: 'important',
            titleAr: 'دعاء العمل الصالح',
            titleEn: 'For Righteous Deeds',
            titleBn: 'সৎকাজের জন্য',
            textAr: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
            textEn: 'O Allah, help me to remember You, to be grateful to You, and to worship You in an excellent manner.',
            textBn: 'হে আল্লাহ! আপনার স্মরণ, কৃতজ্ঞতা ও সুন্দরভাবে ইবাদতে আমাকে সাহায্য করুন।',
            transliteration: 'Allahumma a\'inni \'ala dhikrika wa shukrika wa husni \'ibadatik',
            reference: 'Abu Dawud 1522',
            source: 'Hadith',
            occasion: 'After every prayer',
          ),
          Dua(
            id: 'increase_provision',
            type: 'occasion',
            titleAr: 'دعاء زيادة الرزق',
            titleEn: 'Increase in Provision',
            titleBn: 'রিজিক বৃদ্ধির দোয়া',
            textAr: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
            textEn: 'O Allah, make what is lawful enough for me, as opposed to what is unlawful, and spare me by Your grace, of need of others.',
            textBn: 'হে আল্লাহ! হারাম থেকে হালালকে আমার জন্য যথেষ্ট করে দিন এবং আপনার অনুগ্রহে আমাকে অন্যদের থেকে অমুখাপেক্ষী করুন।',
            transliteration: 'Allahumma-kfini bi-halalika \'an haramik, wa aghnini bi-fadlika \'amman siwak',
            reference: 'Tirmidhi 3563',
            source: 'Hadith',
            occasion: 'For lawful sustenance',
          ),
        ],
      ),

      // 10. Gratitude & Praise Duas
      DuaCategory(
        id: 'gratitude_duas',
        nameAr: 'أدعية الحمد والشكر',
        nameEn: 'Gratitude & Praise',
        nameBn: 'কৃতজ্ঞতা ও প্রশংসার দোয়া',
        descriptionAr: 'أدعية الحمد والشكر لله على النعم',
        descriptionEn: 'Duas for thanking Allah for His blessings',
        descriptionBn: 'আল্লাহর নিয়ামতের জন্য কৃতজ্ঞতার দোয়া',
        iconPath: '🙏',
        duas: [
          Dua(
            id: 'general_praise',
            type: 'daily',
            titleAr: 'الحمد والثناء العام',
            titleEn: 'General Praise',
            titleBn: 'সাধারণ প্রশংসা',
            textAr: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
            textEn: 'All praise is due to Allah, Lord of all the worlds.',
            textBn: 'সমস্ত প্রশংসা সৃষ্টিকুলের রব আল্লাহর জন্য।',
            transliteration: 'Alhamdu lillahi rabbi\'l-\'alamin',
            reference: 'Al-Fatihah 1:2',
            source: 'Quran',
            occasion: 'Anytime for expressing gratitude',
          ),
          Dua(
            id: 'after_blessing',
            type: 'daily',
            titleAr: 'دعاء بعد النعمة',
            titleEn: 'After Receiving a Blessing',
            titleBn: 'নিয়ামত পাওয়ার পর',
            textAr: 'الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ',
            textEn: 'Praise be to Allah by whose favor good deeds are accomplished.',
            textBn: 'সমস্ত প্রশংসা আল্লাহর জন্য যাঁর অনুগ্রহে সৎকাজসমূহ সম্পন্ন হয়।',
            transliteration: 'Alhamdu lillahil-ladhi bi ni\'matihi tatimmu\'s-salihat',
            reference: 'Al-Hakim 1/499',
            source: 'Hadith',
            occasion: 'After receiving good news or blessing',
          ),
        ],
      ),
    ];
  }
}