import '../models/inspiration_models.dart';

class InspirationService {
  static List<InspirationCategory> getCategories() {
    return [
      // 1. Hardship & Relief (Sabr)
      InspirationCategory(
        id: 'hardship_relief',
        nameAr: 'المحن والفرج (الصبر)',
        nameEn: 'Hardship & Relief (Sabr)',
        nameBn: 'দুঃখ ও স্বস্তি (সবর)',
        descriptionAr: 'آيات وأحاديث عن الصبر في المحن ووعد الله بالفرج',
        descriptionEn: 'Verses and Hadiths about patience during trials and Allah\'s promise of relief',
        descriptionBn: 'কষ্টের সময় ধৈর্য এবং আল্লাহর সাহায্যের প্রতিশ্রুতি',
        iconPath: '💪',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ○ إِنَّ مَعَ الْعُسْرِ يُسْرًا',
            textEn: 'For indeed, with hardship [will be] ease. Indeed, with hardship [will be] ease.',
            textBn: 'নিশ্চয়ই কষ্টের সাথে স্বস্তি রয়েছে। নিশ্চয়ই কষ্টের সাথে স্বস্তি রয়েছে।',
            reference: 'Ash-Sharh 94:5-6',
            source: 'Quran',
            transliteration: 'Fa inna ma\'al usri yusra, inna ma\'al usri yusra',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَبَشِّرِ الصَّابِرِينَ ○ الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
            textEn: 'And give good tidings to the patient, Who, when disaster strikes them, say, "Indeed we belong to Allah, and indeed to Him we will return."',
            textBn: 'এবং ধৈর্যশীলদের সুসংবাদ দিন, যারা বিপদ আক্রান্ত হলে বলে, "নিশ্চয়ই আমরা আল্লাহর এবং নিশ্চয়ই আমরা তাঁর নিকট ফিরে যাবো।"',
            reference: 'Al-Baqarah 2:155-156',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا ○ وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ',
            textEn: 'And whoever fears Allah - He will make for him a way out. And will provide for him from where he does not expect.',
            textBn: 'যে আল্লাহকে ভয় করে, তিনি তার জন্য নিস্কৃতির পথ করে দেন। এবং তাকে এমন জায়গা থেকে রিজিক দেন যেখান থেকে সে ধারণাও করতে পারে না।',
            reference: 'At-Talaq 65:2-3',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'عَجَبًا لِأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ وَلَيْسَ ذَاكَ لِأَحَدٍ إِلَّا لِلْمُؤْمِنِ إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ وَإِنْ أَصَابَتْهُ ضَرَّاءُ صَبَرَ فَكَانَ خَيْرًا لَهُ',
            textEn: 'How wonderful is the affair of the believer, for his affairs are all good, and this applies to no one but the believer. If something good happens to him, he is thankful for it and that is good for him. If something bad happens to him, he bears it with patience and that is good for him.',
            textBn: 'মুমিনের ব্যাপারটি কতই না বিস্ময়কর! তার সব বিষয়ই কল্যাণকর। আর এটা মুমিন ছাড়া আর কারো জন্য নয়। যদি তার কোনো ভাল কিছু হয়, সে কৃতজ্ঞতা প্রকাশ করে, তাহলে তা তার জন্য কল্যাণকর। আর যদি কোনো খারাপ কিছু হয়, সে ধৈর্য ধরে, তাহলেও তা তার জন্য কল্যাণকর।',
            reference: 'Sahih Muslim 2999',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'لَا يَقْضِي اللَّهُ لِلْمُؤْمِنِ قَضَاءً إِلَّا كَانَ خَيْرًا لَهُ إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ وَإِنْ أَصَابَتْهُ ضَرَّاءُ صَبَرَ فَكَانَ خَيْرًا لَهُ',
            textEn: 'Allah does not decree anything for the believer except that which is good for him. If good befalls him, he gives thanks and that is good for him. If hardship befalls him, he bears it with patience and that is good for him.',
            textBn: 'আল্লাহ মুমিনের জন্য এমন কোনো ফয়সালা করেন না যা তার জন্য ভালো নয়। যদি তার ভালো কিছু ঘটে, সে কৃতজ্ঞতা প্রকাশ করে এবং এটা তার জন্য ভালো। আর যদি তার কষ্ট আসে, সে ধৈর্য ধরে এবং এটাও তার জন্য ভালো।',
            reference: 'Musnad Ahmad 23489',
            source: 'Ahmad',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَلَنَبْلُوَنَّكُم بِشَيْءٍ مِّنَ الْخَوْفِ وَالْجُوعِ وَنَقْصٍ مِّنَ الْأَمْوَالِ وَالْأَنفُسِ وَالثَّمَرَاتِ ۗ وَبَشِّرِ الصَّابِرِينَ',
            textEn: 'And We will surely test you with something of fear and hunger and a loss of wealth and lives and fruits, but give good tidings to the patient.',
            textBn: 'আর আমি অবশ্যই তোমাদেরকে পরীক্ষা করব কিছু ভয়, ক্ষুধা এবং সম্পদ, জীবন ও ফসলের ক্ষতির মাধ্যমে। তবে ধৈর্যশীলদের সুসংবাদ দাও।',
            reference: 'Al-Baqarah 2:155',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'أَمْ حَسِبْتُمْ أَن تَدْخُلُوا الْجَنَّةَ وَلَمَّا يَأْتِكُم مَّثَلُ الَّذِينَ خَلَوْا مِن قَبْلِكُم ۖ مَّسَّتْهُمُ الْبَأْسَاءُ وَالضَّرَّاءُ وَزُلْزِلُوا',
            textEn: 'Or do you think that you will enter Paradise while such [trial] has not yet come to you as came to those who passed on before you? They were touched by poverty and hardship and were shaken.',
            textBn: 'নাকি তোমরা মনে কর যে তোমরা জান্নাতে প্রবেশ করবে অথচ তোমাদের কাছে এখনো সে রকম পরীক্ষা আসেনি যা তোমাদের পূর্ববর্তীদের কাছে এসেছিল? তাদেরকে স্পর্শ করেছিল দারিদ্র্য ও কষ্ট এবং তাদেরকে কাঁপানো হয়েছিল।',
            reference: 'Al-Baqarah 2:214',
            source: 'Quran',
          ),
        ],
      ),

      // 2. Peace & Anxiety (Sakinah)
      InspirationCategory(
        id: 'peace_anxiety',
        nameAr: 'السكينة والطمأنينة',
        nameEn: 'Peace & Tranquility (Sakinah)',
        nameBn: 'শান্তি ও নিরাপত্তা (সাকীনাহ)',
        descriptionAr: 'آيات وأحاديث عن السكينة وعلاج القلق بالذكر',
        descriptionEn: 'Verses and Hadiths about finding peace and curing anxiety through remembrance',
        descriptionBn: 'স্মরণের মাধ্যমে শান্তি খোঁজা এবং উদ্বেগ নিরাময়',
        iconPath: '🕊️',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
            textEn: 'Unquestionably, by the remembrance of Allah hearts are assured.',
            textBn: 'জেনে রাখো, আল্লাহর স্মরণেই অন্তরসমূহ প্রশান্তি লাভ করে।',
            reference: 'Ar-Ra\'d 13:28',
            source: 'Quran',
            transliteration: 'Ala bidhikri Allahi tatma\'innu al-quloob',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَهُوَ الَّذِي أَنزَلَ السَّكِينَةَ فِي قُلُوبِ الْمُؤْمِنِينَ لِيَزْدَادُوا إِيمَانًا مَّعَ إِيمَانِهِمْ',
            textEn: 'It is He who sent down tranquility into the hearts of the believers that they would increase in faith along with their [present] faith.',
            textBn: 'তিনিই যিনি মুমিনদের অন্তরে সাকীনাহ (শান্তি) নাযিল করেছেন যাতে তারা তাদের ইমানের সাথে আরো ইমান বৃদ্ধি করে।',
            reference: 'Al-Fath 48:4',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَنْ أَكْثَرَ مِنْ قَوْلِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ كَانَ دَوَاءً مِنْ تِسْعَةٍ وَتِسْعِينَ دَاءً أَيْسَرُهَا الْهَمُّ',
            textEn: 'Whoever frequently says "La hawla wa la quwwata illa billah" (There is no power except with Allah), it will be a cure for ninety-nine ailments, the least of which is worry.',
            textBn: 'যে ব্যক্তি বেশি বেশি "লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ" বলে, তা তার জন্য নিরানব্বই রোগের ঔষধ হবে, যার মধ্যে সবচেয়ে ছোটটি হলো দুশ্চিন্তা।',
            reference: 'Al-Hakim 1/672',
            source: 'Hakim',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ',
            textEn: 'So remember Me; I will remember you. And be grateful to Me and do not deny Me.',
            textBn: 'সুতরাং তোমরা আমাকে স্মরণ কর, আমি তোমাদের স্মরণ করবো। আমার প্রতি কৃতজ্ঞতা প্রকাশ কর এবং অকৃতজ্ঞ হয়ো না।',
            reference: 'Al-Baqarah 2:152',
            source: 'Quran',
          ),
        ],
      ),

      // 3. Hope & Mercy (Rahmah)
      InspirationCategory(
        id: 'hope_mercy',
        nameAr: 'الرجاء والرحمة',
        nameEn: 'Hope & Mercy (Rahmah)',
        nameBn: 'আশা ও রহমত',
        descriptionAr: 'آيات وأحاديث عن سعة رحمة الله ومغفرته',
        descriptionEn: 'Verses and Hadiths about Allah\'s vast mercy and forgiveness',
        descriptionBn: 'আল্লাহর ব্যাপক রহমত ও ক্ষমা সম্পর্কে',
        iconPath: '🤲',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ',
            textEn: 'Say, "O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful."',
            textBn: 'বলুন, "হে আমার বান্দারা! যারা নিজেদের উপর বাড়াবাড়ি করেছ, তোমরা আল্লাহর রহমত থেকে নিরাশ হয়ো না। নিশ্চয়ই আল্লাহ সব গুনাহ মাফ করে দেন। নিশ্চয়ই তিনি ক্ষমাশীল, দয়ালু।"',
            reference: 'Az-Zumar 39:53',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ فَسَأَكْتُبُهَا لِلَّذِينَ يَتَّقُونَ وَيُؤْتُونَ الزَّكَاةَ وَالَّذِينَ هُم بِآيَاتِنَا يُؤْمِنُونَ',
            textEn: 'And My mercy encompasses all things. So I will decree it [especially] for those who fear Me and give zakah and those who believe in Our verses.',
            textBn: 'আমার রহমত সব কিছুকে ঘিরে রেখেছে। সুতরাং আমি তা লিখে দেবো তাদের জন্য যারা আমাকে ভয় করে, যাকাত দেয় এবং আমার আয়াতসমূহে বিশ্বাস করে।',
            reference: 'Al-A\'raf 7:156',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنَّ اللَّهَ كَتَبَ كِتَابًا قَبْلَ أَنْ يَخْلُقَ الْخَلْقَ إِنَّ رَحْمَتِي سَبَقَتْ غَضَبِي فَهُوَ مَكْتُوبٌ عِنْدَهُ فَوْقَ الْعَرْشِ',
            textEn: 'Allah wrote in a book before He created the creation: My mercy prevails over My wrath, and it is written with Him above the Throne.',
            textBn: 'আল্লাহ সৃষ্টিজগত সৃষ্টির পূর্বে একটি কিতাব লিখেছেন: আমার রহমত আমার রাগকে পরাজিত করেছে। আর এটি তাঁর কাছে আরশের উপর লেখা আছে।',
            reference: 'Sahih Bukhari 7422',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'لَوْ يَعْلَمُ الْمُؤْمِنُ مَا عِنْدَ اللَّهِ مِنْ الْعُقُوبَةِ مَا طَمِعَ بِجَنَّتِهِ أَحَدٌ وَلَوْ يَعْلَمُ الْكَافِرُ مَا عِنْدَ اللَّهِ مِنْ الرَّحْمَةِ مَا قَنَطَ مِنْ جَنَّتِهِ أَحَدٌ',
            textEn: 'If the believer knew what punishment Allah has, no one would hope for His Paradise. And if the disbeliever knew what mercy Allah has, no one would despair of His Paradise.',
            textBn: 'যদি মুমিন জানত আল্লাহর কাছে কী শাস্তি আছে, তাহলে কেউ তাঁর জান্নাতের আশা করত না। আর যদি কাফের জানত আল্লাহর কাছে কী রহমত আছে, তাহলে কেউ তাঁর জান্নাত থেকে নিরাশ হত না।',
            reference: 'Sahih Muslim 2755',
            source: 'Muslim',
          ),
        ],
      ),

      // 4. Trust in Allah (Tawakkul)
      InspirationCategory(
        id: 'trust_allah',
        nameAr: 'التوكل على الله',
        nameEn: 'Trust in Allah (Tawakkul)',
        nameBn: 'আল্লাহর উপর ভরসা (তাওয়াক্কুল)',
        descriptionAr: 'آيات وأحاديث عن التوكل على الله والثقة بتدبيره',
        descriptionEn: 'Verses and Hadiths about trusting in Allah and having confidence in His planning',
        descriptionBn: 'আল্লাহর পরিকল্পনায় বিশ্বাস ও ভরসা',
        iconPath: '🤍',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ ۚ إِنَّ اللَّهَ بَالِغُ أَمْرِهِ ۚ قَدْ جَعَلَ اللَّهُ لِكُلِّ شَيْءٍ قَدْرًا',
            textEn: 'And whoever relies upon Allah - then He is sufficient for him. Indeed, Allah will accomplish His purpose. Allah has already set for everything a [decreed] extent.',
            textBn: 'যে আল্লাহর উপর ভরসা করে, তার জন্য আল্লাহই যথেষ্ট। নিশ্চয়ই আল্লাহ তাঁর কাজ সম্পন্ন করবেন। আল্লাহ প্রতিটি বস্তুর জন্য একটি পরিমাণ নির্ধারণ করেছেন।',
            reference: 'At-Talaq 65:3',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ ۚ إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ',
            textEn: 'And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely [upon Him].',
            textBn: 'অতঃপর যখন তুমি সংকল্পবদ্ধ হও, তখন আল্লাহর উপর ভরসা কর। নিশ্চয়ই আল্লাহ তাদের ভালোবাসেন যারা তাঁর উপর ভরসা করে।',
            reference: 'Aal-e-Imran 3:159',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
            textEn: 'Sufficient for us is Allah, and [He is] the best Disposer of affairs.',
            textBn: 'আল্লাহই আমাদের জন্য যথেষ্ট এবং তিনি কতই না উত্তম কর্মবিধায়ক।',
            reference: 'Aal-e-Imran 3:173',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'لَوْ أَنَّكُمْ تَوَكَّلْتُمْ عَلَى اللَّهِ حَقَّ تَوَكُّلِهِ لَرَزَقَكُمْ كَمَا يَرْزُقُ الطَّيْرَ تَغْدُو خِمَاصًا وَتَرُوحُ بِطَانًا',
            textEn: 'If you were to rely upon Allah with true reliance, He would provide for you just as He provides for the birds; they go out in the morning with empty stomachs and return full.',
            textBn: 'যদি তোমরা আল্লাহর উপর প্রকৃত ভরসা করতে, তাহলে তিনি তোমাদেরকে রিজিক দিতেন যেমন পাখিদেরকে দেন; তারা সকালে খালি পেটে বের হয় এবং সন্ধ্যায় পেট ভরে ফিরে আসে।',
            reference: 'Jami\' at-Tirmidhi 2344',
            source: 'Tirmidhi',
          ),
        ],
      ),

      // 5. Gratitude & Blessings (Shukr)
      InspirationCategory(
        id: 'gratitude_blessings',
        nameAr: 'الشكر والنعم',
        nameEn: 'Gratitude & Blessings (Shukr)',
        nameBn: 'কৃতজ্ঞতা ও নিয়ামত (শুকর)',
        descriptionAr: 'آيات وأحاديث عن الشكر وتذكر النعم المخفية',
        descriptionEn: 'Verses and Hadiths about gratitude and remembering hidden blessings',
        descriptionBn: 'কৃতজ্ঞতা এবং গোপন নিয়ামতের স্মরণ',
        iconPath: '🌟',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ ۖ وَلَئِن كَفَرْتُمْ إِنَّ عَذَابِي لَشَدِيدٌ',
            textEn: 'If you are grateful, I will certainly give you more. But if you are ungrateful, then My punishment is severe.',
            textBn: 'যদি তোমরা কৃতজ্ঞতা প্রকাশ কর, তাহলে আমি অবশ্যই তোমাদের আরো দেবো। আর যদি অকৃতজ্ঞ হও, তাহলে নিশ্চয়ই আমার শাস্তি কঠোর।',
            reference: 'Ibrahim 14:7',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَإِذْ تَأَذَّنَ رَبُّكُمْ لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ',
            textEn: 'And [remember] when your Lord proclaimed, "If you are grateful, I will surely increase you [in favor]."',
            textBn: 'আর স্মরণ কর, যখন তোমাদের রব ঘোষণা করলেন, "যদি তোমরা কৃতজ্ঞ হও, আমি অবশ্যই তোমাদের বাড়িয়ে দেব।"',
            reference: 'Ibrahim 14:7',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَنْ لَمْ يَشْكُرِ النَّاسَ لَمْ يَشْكُرِ اللَّهَ',
            textEn: 'Whoever does not thank people has not thanked Allah.',
            textBn: 'যে মানুষের কৃতজ্ঞতা প্রকাশ করে না সে আল্লাহরও কৃতজ্ঞতা প্রকাশ করে না।',
            reference: 'Sunan Abi Dawud 4811',
            source: 'Abu Dawud',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَقَلِيلٌ مِّنْ عِبَادِيَ الشَّكُورُ',
            textEn: 'And few of My servants are grateful.',
            textBn: 'আর আমার বান্দাদের মধ্যে অল্পই কৃতজ্ঞ।',
            reference: 'Saba 34:13',
            source: 'Quran',
          ),
        ],
      ),

      // 6. Character & Ethics (Akhlaq)
      InspirationCategory(
        id: 'character_ethics',
        nameAr: 'الأخلاق والآداب',
        nameEn: 'Character & Ethics (Akhlaq)',
        nameBn: 'চরিত্র ও নৈতিকতা (আখলাক)',
        descriptionAr: 'آيات وأحاديث عن حسن الخلق والآداب الإسلامية',
        descriptionEn: 'Verses and Hadiths about good character and Islamic ethics',
        descriptionBn: 'উত্তম চরিত্র এবং ইসলামী শিষ্টাচার',
        iconPath: '🌺',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ',
            textEn: 'And indeed, you are of a great moral character.',
            textBn: 'আর নিশ্চয়ই তুমি মহান চরিত্রের অধিকারী।',
            reference: 'Al-Qalam 68:4',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ وَأَعْرِضْ عَنِ الْجَاهِلِينَ',
            textEn: 'Take what is given freely, enjoin what is good, and turn away from the ignorant.',
            textBn: 'ক্ষমা করে দাও, ভালো কাজের আদেশ দাও এবং মূর্খদের থেকে মুখ ফিরিয়ে নাও।',
            reference: 'Al-A\'raf 7:199',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنَّمَا بُعِثْتُ لِأُتَمِّمَ مَكَارِمَ الْأَخْلَاقِ',
            textEn: 'I was sent only to perfect good character.',
            textBn: 'আমি শুধুমাত্র উত্তম চরিত্রের পূর্ণতার জন্য প্রেরিত হয়েছি।',
            reference: 'Al-Adab Al-Mufrad 273',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'لَيْسَ الْمُؤْمِنُ بِالطَّعَّانِ وَلَا اللَّعَّانِ وَلَا الْفَاحِشِ وَلَا الْبَذِيءِ',
            textEn: 'The believer is not one who slanders, curses, or speaks in an obscene or foul manner.',
            textBn: 'মুমিন সে নয় যে মন্দ কথা বলে, অভিশাপ দেয়, অশ্লীল বা কুৎসিত কথা বলে।',
            reference: 'Jami\' at-Tirmidhi 1977',
            source: 'Tirmidhi',
          ),
        ],
      ),

      // 7. Success & Productivity
      InspirationCategory(
        id: 'success_productivity',
        nameAr: 'النجاح والإنتاجية',
        nameEn: 'Success & Productivity',
        nameBn: 'সাফল্য ও উৎপাদনশীলতা',
        descriptionAr: 'آيات وأحاديث عن البركة في الوقت والمال والإحسان في العمل',
        descriptionEn: 'Verses and Hadiths about blessing in time and wealth, and excellence in work',
        descriptionBn: 'সময় ও সম্পদে বরকত এবং কাজে উৎকর্ষতা',
        iconPath: '📈',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَأَن لَّيْسَ لِلْإِنسَانِ إِلَّا مَا سَعَىٰ',
            textEn: 'And that there is nothing for man except what he strives for.',
            textBn: 'আর মানুষ যা চেষ্টা করে তা ছাড়া আর কিছুই পায় না।',
            reference: 'An-Najm 53:39',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ',
            textEn: 'Indeed, Allah loves when one of you does a job, that he does it with excellence.',
            textBn: 'নিশ্চয়ই আল্লাহ ভালোবাসেন যখন তোমাদের কেউ কোনো কাজ করে, তখন সে যেন তা নিপুণতার সাথে করে।',
            reference: 'Shu\'ab al-Iman 4928',
            source: 'Bayhaqi',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَمَن يُؤْتَ الْحِكْمَةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا',
            textEn: 'And whoever is given wisdom has certainly been given much good.',
            textBn: 'আর যাকে হিকমত দান করা হয়েছে, তাকে অনেক কল্যাণ দেয়া হয়েছে।',
            reference: 'Al-Baqarah 2:269',
            source: 'Quran',
          ),
        ],
      ),

      // 8. Family & Love
      InspirationCategory(
        id: 'family_love',
        nameAr: 'الأسرة والمحبة',
        nameEn: 'Family & Love',
        nameBn: 'পরিবার ও ভালোবাসা',
        descriptionAr: 'آيات وأحاديث عن حقوق الوالدين والأزواج وصلة الرحم',
        descriptionEn: 'Verses and Hadiths about rights of parents, spouses, and family bonds',
        descriptionBn: 'পিতামাতা, স্বামী-স্ত্রী এবং আত্মীয়তার সম্পর্ক',
        iconPath: '❤️',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَقَضَىٰ رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا',
            textEn: 'And your Lord has decreed that you worship none but Him, and be kind to parents.',
            textBn: 'আর তোমার রব নির্দেশ দিয়েছেন যে, তিনি ছাড়া আর কারো ইবাদত করো না এবং পিতামাতার সাথে সদ্ব্যবহার করো।',
            reference: 'Al-Isra 17:23',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'الْجَنَّةُ تَحْتَ أَقْدَامِ الْأُمَّهَاتِ',
            textEn: 'Paradise lies at the feet of mothers.',
            textBn: 'মায়ের পায়ের নিচে সন্তানের জান্নাত।',
            reference: 'Sunan an-Nasa\'i 3104',
            source: 'Nasa\'i',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً',
            textEn: 'And among His signs is that He created for you from yourselves mates that you may find tranquility in them; and He placed between you affection and mercy.',
            textBn: 'আর তাঁর নিদর্শনাবলীর মধ্যে রয়েছে যে, তিনি তোমাদের জন্য তোমাদের মধ্য থেকেই স্ত্রী সৃষ্টি করেছেন, যাতে তোমরা তাদের কাছে শান্তি পাও। আর তোমাদের মধ্যে ভালোবাসা ও দয়া সৃষ্টি করেছেন।',
            reference: 'Ar-Rum 30:21',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ وَأَنَا خَيْرُكُمْ لِأَهْلِي',
            textEn: 'The best of you are those who are best to their families, and I am the best of you to my family.',
            textBn: 'তোমাদের মধ্যে সে-ই উত্তম যে তার পরিবারের জন্য উত্তম। আর আমি আমার পরিবারের জন্য তোমাদের মধ্যে সবচেয়ে উত্তম।',
            reference: 'Jami\' at-Tirmidhi 3895',
            source: 'Tirmidhi',
          ),
        ],
      ),

      // 9. Purpose of Life
      InspirationCategory(
        id: 'purpose_life',
        nameAr: 'الغاية من الحياة',
        nameEn: 'Purpose of Life',
        nameBn: 'জীবনের উদ্দেশ্য',
        descriptionAr: 'آيات وأحاديث عن دور الإنسان كخليفة في الأرض وطبيعة الحياة الدنيا',
        descriptionEn: 'Verses and Hadiths about our role as stewards on Earth and the nature of worldly life',
        descriptionBn: 'পৃথিবীতে আমাদের দায়িত্ব এবং পার্থিব জীবনের প্রকৃতি',
        iconPath: '🎯',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ',
            textEn: 'And I did not create the jinn and mankind except to worship Me.',
            textBn: 'আমি জিন ও মানুষকে কেবল আমার ইবাদতের জন্যই সৃষ্টি করেছি।',
            reference: 'Az-Zariyat 51:56',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'إِنِّي جَاعِلٌ فِي الْأَرْضِ خَلِيفَةً',
            textEn: 'Indeed, I will make upon the earth a successor (khalifa).',
            textBn: 'নিশ্চয়ই আমি পৃথিবীতে একজন প্রতিনিধি (খলিফা) নিয়োগ করব।',
            reference: 'Al-Baqarah 2:30',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنَّ الدُّنْيَا حُلْوَةٌ خَضِرَةٌ وَإِنَّ اللَّهَ مُسْتَخْلِفُكُمْ فِيهَا فَيَنْظُرُ كَيْفَ تَعْمَلُونَ',
            textEn: 'The world is sweet and green, and Allah has appointed you as His stewards over it to see how you will act.',
            textBn: 'দুনিয়া মিষ্টি ও সবুজ, আর আল্লাহ তোমাদের এর উপর তাঁর প্রতিনিধি বানিয়েছেন দেখার জন্য যে তোমরা কীভাবে কাজ করো।',
            reference: 'Sahih Muslim 2742',
            source: 'Muslim',
          ),
        ],
      ),

      // 10. The Power of Prayer (Dua)
      InspirationCategory(
        id: 'power_prayer',
        nameAr: 'قوة الدعاء',
        nameEn: 'The Power of Prayer (Dua)',
        nameBn: 'দোয়ার শক্তি',
        descriptionAr: 'آيات وأحاديث عن قوة الدعاء وتغيير القدر بالدعاء',
        descriptionEn: 'Verses and Hadiths about the power of prayer and how dua can change destiny',
        descriptionBn: 'দোয়ার শক্তি এবং কীভাবে দোয়া ভাগ্য পরিবর্তন করতে পারে',
        iconPath: '🤲',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ',
            textEn: 'And your Lord says, "Call upon Me; I will respond to you."',
            textBn: 'আর তোমাদের রব বলেছেন, "তোমরা আমার কাছে দোয়া কর, আমি তোমাদের দোয়া কবুল করবো।"',
            reference: 'Ghafir 40:60',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'لَا يَرُدُّ الْقَضَاءَ إِلَّا الدُّعَاءُ وَلَا يَزِيدُ فِي الْعُمُرِ إِلَّا الْبِرُّ',
            textEn: 'Nothing can change the Divine decree except prayer (dua), and nothing increases the lifespan except righteousness.',
            textBn: 'দোয়া ছাড়া আল্লাহর ফয়সালা পরিবর্তন হয় না এবং নেকী ছাড়া আয়ু বৃদ্ধি পায় না।',
            reference: 'Sunan Ibn Majah 90',
            source: 'Ibn Majah',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ',
            textEn: 'And when My servants ask you concerning Me, indeed I am near. I respond to the invocation of the supplicant when he calls upon Me.',
            textBn: 'আর যখন আমার বান্দারা তোমার কাছে আমার সম্পর্কে জিজ্ঞেস করে, তখন আমি অবশ্যই নিকটে আছি। আমি প্রার্থনাকারীর ডাকে সাড়া দেই যখন সে আমাকে ডাকে।',
            reference: 'Al-Baqarah 2:186',
            source: 'Quran',
          ),
        ],
      ),

      // 11. Knowledge & Learning (Ilm)
      InspirationCategory(
        id: 'knowledge_learning',
        nameAr: 'العلم والتعلم',
        nameEn: 'Knowledge & Learning (Ilm)',
        nameBn: 'জ্ঞান ও শিক্ষা (ইলম)',
        descriptionAr: 'آيات وأحاديث عن فضل العلم وطلب المعرفة',
        descriptionEn: 'Verses and Hadiths about the virtue of knowledge and seeking learning',
        descriptionBn: 'জ্ঞানের মর্যাদা এবং জ্ঞান অর্জনের গুরুত্ব',
        iconPath: '📚',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',
            textEn: 'Read in the name of your Lord who created.',
            textBn: 'পড় তোমার রবের নামে যিনি সৃষ্টি করেছেন।',
            reference: 'Al-Alaq 96:1',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
            textEn: 'Seeking knowledge is obligatory upon every Muslim.',
            textBn: 'প্রত্যেক মুসলিমের জন্য জ্ঞান অর্জন ফরজ।',
            reference: 'Sunan Ibn Majah 224',
            source: 'Ibn Majah',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَقُل رَّبِّ زِدْنِي عِلْمًا',
            textEn: 'And say: My Lord, increase me in knowledge.',
            textBn: 'আর বল: হে আমার রব, আমার জ্ঞান বৃদ্ধি করে দাও।',
            reference: 'Ta-Ha 20:114',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
            textEn: 'Whoever travels a path in search of knowledge, Allah will make easy for him a path to Paradise.',
            textBn: 'যে ব্যক্তি জ্ঞান অন্বেষণে পথ চলে, আল্লাহ তার জন্য জান্নাতের পথ সহজ করে দেন।',
            reference: 'Sahih Muslim 2699',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنكُمْ وَالَّذِينَ أُوتُوا الْعِلْمَ دَرَجَاتٍ',
            textEn: 'Allah will raise those who have believed among you and those who were given knowledge, by degrees.',
            textBn: 'আল্লাহ তোমাদের মধ্যে যারা ঈমান এনেছে এবং যাদের জ্ঞান দেওয়া হয়েছে তাদের মর্যাদা উন্নত করবেন।',
            reference: 'Al-Mujadilah 58:11',
            source: 'Quran',
          ),
        ],
      ),

      // 12. Health & Well-being (Sihha)
      InspirationCategory(
        id: 'health_wellbeing',
        nameAr: 'الصحة والعافية',
        nameEn: 'Health & Well-being (Sihha)',
        nameBn: 'স্বাস্থ্য ও সুস্থতা (সিহহা)',
        descriptionAr: 'آيات وأحاديث عن أهمية الصحة الجسدية والنفسية',
        descriptionEn: 'Verses and Hadiths about the importance of physical and mental health',
        descriptionBn: 'শারীরিক ও মানসিক স্বাস্থ্যের গুরুত্ব',
        iconPath: '🌿',
        contents: [
          InspirationContent(
            type: 'hadith',
            textAr: 'نِعْمَتَانِ مَغْبُونٌ فِيهِمَا كَثِيرٌ مِنَ النَّاسِ الصِّحَّةُ وَالْفَرَاغُ',
            textEn: 'There are two blessings in which many people are deceived: health and free time.',
            textBn: 'দুটি নিয়ামতে অনেক মানুষ ধোকায় পড়ে: স্বাস্থ্য এবং অবসর সময়।',
            reference: 'Sahih al-Bukhari 6412',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَلَا تُلْقُوا بِأَيْدِيكُمْ إِلَى التَّهْلُكَةِ',
            textEn: 'And do not throw [yourselves] with your [own] hands into destruction.',
            textBn: 'আর তোমরা নিজেদের হাতে নিজেদেরকে ধ্বংসের মুখে ঠেলে দিও না।',
            reference: 'Al-Baqarah 2:195',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنَّ لِجَسَدِكَ عَلَيْكَ حَقًّا',
            textEn: 'Indeed, your body has a right over you.',
            textBn: 'নিশ্চয়ই তোমার শরীরের তোমার উপর অধিকার রয়েছে।',
            reference: 'Sahih al-Bukhari 1968',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَكُلُوا وَاشْرَبُوا وَلَا تُسْرِفُوا إِنَّهُ لَا يُحِبُّ الْمُسْرِفِينَ',
            textEn: 'And eat and drink, but be not excessive. Indeed, He likes not those who commit excess.',
            textBn: 'আর তোমরা খাও ও পান কর, কিন্তু অপব্যয় করো না। নিশ্চয়ই তিনি অপব্যয়কারীদের পছন্দ করেন না।',
            reference: 'Al-A\'raf 7:31',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَا مَلَأَ آدَمِيٌّ وِعَاءً شَرًّا مِنْ بَطْنِهِ حَسْبُ الْآدَمِيِّ لُقَيْمَاتٌ يُقِمْنَ صُلْبَهُ',
            textEn: 'No human fills a vessel worse than his stomach. It is sufficient for the son of Adam to eat a few mouthfuls to keep his spine straight.',
            textBn: 'মানুষ পেটের চেয়ে খারাপ কোনো পাত্র ভরে না। আদম সন্তানের জন্য তার মেরুদণ্ড সোজা রাখার জন্য কয়েক গ্রাসই যথেষ্ট।',
            reference: 'Jami\' at-Tirmidhi 2380',
            source: 'Tirmidhi',
          ),
        ],
      ),

      // 13. Forgiveness & Repentance (Tawbah)
      InspirationCategory(
        id: 'forgiveness_repentance',
        nameAr: 'الاستغفار والتوبة',
        nameEn: 'Forgiveness & Repentance (Tawbah)',
        nameBn: 'ক্ষমা ও তওবা',
        descriptionAr: 'آيات وأحاديث عن الاستغفار وفضل التوبة النصوح',
        descriptionEn: 'Verses and Hadiths about seeking forgiveness and sincere repentance',
        descriptionBn: 'ক্ষমা প্রার্থনা এবং সত্যিকারের তওবার মর্যাদা',
        iconPath: '🤍',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَأَنِ اسْتَغْفِرُوا رَبَّكُمْ ثُمَّ تُوبُوا إِلَيْهِ يُمَتِّعْكُم مَّتَاعًا حَسَنًا',
            textEn: 'And seek forgiveness of your Lord and then repent to Him; He will give you good enjoyment.',
            textBn: 'আর তোমাদের রবের কাছে ক্ষমা চাও, অতঃপর তাঁর কাছে তওবা কর; তিনি তোমাদের সুন্দর জীবন দান করবেন।',
            reference: 'Hud 11:3',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'كُلُّ بَنِي آدَمَ خَطَّاءٌ وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ',
            textEn: 'All the sons of Adam are sinners, but the best of sinners are those who repent.',
            textBn: 'আদম সন্তানেরা সবাই পাপী, কিন্তু পাপীদের মধ্যে সবচেয়ে ভালো তারা যারা তওবা করে।',
            reference: 'Jami\' at-Tirmidhi 2499',
            source: 'Tirmidhi',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'التَّائِبُ مِنَ الذَّنْبِ كَمَنْ لَا ذَنْبَ لَهُ',
            textEn: 'The one who repents from sin is like one who has no sin.',
            textBn: 'পাপ থেকে তওবাকারী এমন ব্যক্তির মত যার কোনো পাপ নেই।',
            reference: 'Sunan Ibn Majah 4250',
            source: 'Ibn Majah',
          ),
        ],
      ),

      // 14. Death & Afterlife (Akhirah)
      InspirationCategory(
        id: 'death_afterlife',
        nameAr: 'الموت والآخرة',
        nameEn: 'Death & Afterlife (Akhirah)',
        nameBn: 'মৃত্যু ও পরকাল (আখিরাত)',
        descriptionAr: 'آيات وأحاديث عن الموت والاستعداد للآخرة',
        descriptionEn: 'Verses and Hadiths about death and preparation for the afterlife',
        descriptionBn: 'মৃত্যু এবং পরকালের প্রস্তুতি',
        iconPath: '🕌',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ',
            textEn: 'Every soul will taste death.',
            textBn: 'প্রতিটি প্রাণই মৃত্যুর স্বাদ গ্রহণ করবে।',
            reference: 'Ali \' Imran 3:185',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'أَكْثِرُوا ذِكْرَ هَاذِمِ اللَّذَّاتِ الْمَوْتَ',
            textEn: 'Remember often the destroyer of pleasures: death.',
            textBn: 'তোমরা বেশি বেশি স্মরণ কর আনন্দ বিনাশকারী মৃত্যুকে।',
            reference: 'Jami\' at-Tirmidhi 2307',
            source: 'Tirmidhi',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ',
            textEn: 'And the worldly life is not but the enjoyment of delusion.',
            textBn: 'আর পার্থিব জীবন তো কেবল ধোঁকার সম্পদ মাত্র।',
            reference: 'Ali \' Imran 3:185',
            source: 'Quran',
          ),
        ],
      ),

      // 15. Social Justice & Equality (Adl)
      InspirationCategory(
        id: 'social_justice',
        nameAr: 'العدالة الاجتماعية والمساواة',
        nameEn: 'Social Justice & Equality (Adl)',
        nameBn: 'সামাজিক ন্যায়বিচার ও সমতা (আদল)',
        descriptionAr: 'آيات وأحاديث عن العدل والإحسان ومساعدة الفقراء',
        descriptionEn: 'Verses and Hadiths about justice, fairness, and helping the poor',
        descriptionBn: 'ন্যায়বিচার, সুবিচার এবং দরিদ্রদের সাহায্য',
        iconPath: '⚖️',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ',
            textEn: 'Indeed, Allah orders justice and good conduct.',
            textBn: 'নিশ্চয়ই আল্লাহ ন্যায়বিচার ও সদাচরণের আদেশ দেন।',
            reference: 'An-Nahl 16:90',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ وَتَرَاحُمِهِمْ وَتَعَاطُفِهِمْ مَثَلُ الْجَسَدِ إِذَا اشْتَكَى مِنْهُ عُضْوٌ تَدَاعَى لَهُ سَائِرُ الْجَسَدِ بِالسَّهَرِ وَالْحُمَّى',
            textEn: 'The example of believers in their affection, mercy, and compassion for each other is that of a body. When a limb suffers, the whole body responds to it with wakefulness and fever.',
            textBn: 'মুমিনদের পারস্পরিক ভালোবাসা, দয়া ও সহানুভূতির উদাহরণ একটি শরীরের মত। যখন একটি অঙ্গ অসুস্থ হয়, তখন পুরো শরীর জাগরণ ও জ্বর নিয়ে সাড়া দেয়।',
            reference: 'Sahih Muslim 2586',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَيُطْعِمُونَ الطَّعَامَ عَلَىٰ حُبِّهِ مِسْكِينًا وَيَتِيمًا وَأَسِيرًا',
            textEn: 'And they give food in spite of love for it to the needy, the orphan, and the captive.',
            textBn: 'আর তারা খাদ্যের প্রতি ভালোবাসা সত্ত্বেও তা দরিদ্র, এতিম ও বন্দীকে দান করে।',
            reference: 'Al-Insan 76:8',
            source: 'Quran',
          ),
        ],
      ),

      // 16. Unity & Brotherhood (Ukhuwah)
      InspirationCategory(
        id: 'unity_brotherhood',
        nameAr: 'الوحدة والأخوة',
        nameEn: 'Unity & Brotherhood (Ukhuwah)',
        nameBn: 'একতা ও ভ্রাতৃত্ব (উখুওয়াহ)',
        descriptionAr: 'آيات وأحاديث عن أهمية الوحدة والأخوة بين المسلمين',
        descriptionEn: 'Verses and Hadiths about the importance of unity and brotherhood among Muslims',
        descriptionBn: 'মুসলিমদের মধ্যে একতা ও ভ্রাতৃত্বের গুরুত্ব',
        iconPath: '🤝',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ',
            textEn: 'The believers are but brothers.',
            textBn: 'মুমিনরা তো ভাই ভাই।',
            reference: 'Al-Hujurat 49:10',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'الْمُسْلِمُ أَخُو الْمُسْلِمِ لَا يَظْلِمُهُ وَلَا يُسْلِمُهُ',
            textEn: 'A Muslim is the brother of a Muslim. He neither oppresses him nor humiliates him.',
            textBn: 'মুসলিম মুসলিমের ভাই। সে তার উপর জুলুম করে না এবং তাকে অপমানিত করে না।',
            reference: 'Sahih Muslim 2564',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',
            textEn: 'And hold firmly to the rope of Allah all together and do not become divided.',
            textBn: 'আর তোমরা সকলে আল্লাহর রজ্জুকে দৃঢ়ভাবে ধর এবং বিচ্ছিন্ন হয়ো না।',
            reference: 'Ali \'Imran 3:103',
            source: 'Quran',
          ),
        ],
      ),

      // 17. Success & Achievement (Najah)
      InspirationCategory(
        id: 'success_achievement',
        nameAr: 'النجاح والإنجاز',
        nameEn: 'Success & Achievement (Najah)',
        nameBn: 'সাফল্য ও অর্জন (নাজাহ)',
        descriptionAr: 'آيات وأحاديث عن الطريق للنجاح والتوفيق من الله',
        descriptionEn: 'Verses and Hadiths about the path to success and divine guidance',
        descriptionBn: 'সাফল্যের পথ এবং আল্লাহর তৌফিক',
        iconPath: '🏆',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَمَن يَتَّقِ اللَّهَ وَيُصْلِحْ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
            textEn: 'And whoever fears Allah and reforms - there will be no fear concerning them, nor will they grieve.',
            textBn: 'আর যে আল্লাহকে ভয় করে এবং সংশোধন করে তার কোনো ভয় নেই এবং তারা দুঃখিত হবে না।',
            reference: 'Al-An\'am 6:48',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَا نَقَصَ مَالٌ مِنْ صَدَقَةٍ وَمَا زَادَ اللَّهُ عَبْدًا بِعَفْوٍ إِلَّا عِزًّا وَمَا تَوَاضَعَ أَحَدٌ لِلَّهِ إِلَّا رَفَعَهُ اللَّهُ',
            textEn: 'No wealth decreases by giving charity, Allah increases the honor of him who forgives, and no one humbles himself for Allah except that Allah elevates him.',
            textBn: 'দান-খয়রাতে সম্পদ কমে না। যে ক্ষমা করে আল্লাহ তার সম্মান বাড়ান। যে আল্লাহর জন্য বিনয়ী হয় আল্লাহ তাকে উঁচু করেন।',
            reference: 'Sahih Muslim 2588',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ',
            textEn: 'But perhaps you hate a thing and it is good for you.',
            textBn: 'হতে পারে তোমরা কোনো বিষয়কে অপছন্দ করছ অথচ তা তোমাদের জন্য ভালো।',
            reference: 'Al-Baqarah 2:216',
            source: 'Quran',
          ),
        ],
      ),

      // 18. Love & Compassion (Rahmah)
      InspirationCategory(
        id: 'love_compassion',
        nameAr: 'المحبة والرحمة',
        nameEn: 'Love & Compassion (Rahmah)',
        nameBn: 'ভালোবাসা ও করুণা (রহমত)',
        descriptionAr: 'آيات وأحاديث عن المحبة والرحمة في الإسلام',
        descriptionEn: 'Verses and Hadiths about love and compassion in Islam',
        descriptionBn: 'ইসলামে ভালোবাসা ও করুণার গুরুত্ব',
        iconPath: '❤️',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَجَعَلْنَا فِي قُلُوبِ الَّذِينَ اتَّبَعُوهُ رَأْفَةً وَرَحْمَةً',
            textEn: 'And We placed in the hearts of those who followed him compassion and mercy.',
            textBn: 'আর যারা তার অনুসরণ করেছিল তাদের অন্তরে আমি দয়া ও করুণা রেখেছিলাম।',
            reference: 'Al-Hadid 57:27',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ ارْحَمُوا مَنْ فِي الْأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
            textEn: 'The merciful will be shown mercy by the Merciful One. Be merciful to others and you will receive mercy from the One in the heavens.',
            textBn: 'দয়ালুদের প্রতি পরম দয়ালু (আল্লাহ) দয়া করেন। তোমরা পৃথিবীর অধিবাসীদের প্রতি দয়া কর, আকাশে যিনি আছেন তিনি তোমাদের প্রতি দয়া করবেন।',
            reference: 'Jami\' at-Tirmidhi 1924',
            source: 'Tirmidhi',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'لَيْسَ مِنَّا مَنْ لَمْ يَرْحَمْ صَغِيرَنَا وَيُوَقِّرْ كَبِيرَنَا',
            textEn: 'He is not one of us who does not show mercy to our young and does not respect our elders.',
            textBn: 'সে আমাদের অন্তর্ভুক্ত নয় যে আমাদের ছোটদের প্রতি দয়া করে না এবং বড়দের সম্মান করে না।',
            reference: 'Jami\' at-Tirmidhi 1919',
            source: 'Tirmidhi',
          ),
        ],
      ),

      // 19. Wealth & Charity (Zakat)
      InspirationCategory(
        id: 'wealth_charity',
        nameAr: 'المال والصدقة',
        nameEn: 'Wealth & Charity (Zakat)',
        nameBn: 'সম্পদ ও দান (যাকাত)',
        descriptionAr: 'آيات وأحاديث عن إدارة المال والعطاء والزكاة',
        descriptionEn: 'Verses and Hadiths about money management, giving, and charity',
        descriptionBn: 'অর্থ ব্যবস্থাপনা, দান ও যাকাতের গুরুত্ব',
        iconPath: '💰',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'مَّثَلُ الَّذِينَ يُنفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللَّهِ كَمَثَلِ حَبَّةٍ أَنبَتَتْ سَبْعَ سَنَابِلَ فِي كُلِّ سُنبُلَةٍ مِّائَةُ حَبَّةٍ',
            textEn: 'The example of those who spend their wealth in the way of Allah is like a seed which grows seven spikes; in each spike is a hundred grains.',
            textBn: 'যারা আল্লাহর পথে নিজেদের সম্পদ ব্যয় করে তাদের উদাহরণ একটি বীজের মত যা সাতটি শীষ উৎপন্ন করে; প্রতিটি শীষে একশত দানা।',
            reference: 'Al-Baqarah 2:261',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَا مِنْ يَوْمٍ يُصْبِحُ الْعِبَادُ فِيهِ إِلَّا مَلَكَانِ يَنْزِلَانِ فَيَقُولُ أَحَدُهُمَا اللَّهُمَّ أَعْطِ مُنْفِقًا خَلَفًا وَيَقُولُ الْآخَرُ اللَّهُمَّ أَعْطِ مُمْسِكًا تَلَفًا',
            textEn: 'Every day two angels come down and one of them says, "O Allah! Compensate the person who spends in Your cause," and the other says, "O Allah! Destroy the wealth of the miser."',
            textBn: 'প্রতিদিন দুই ফেরেশতা নেমে আসেন। একজন বলেন, "হে আল্লাহ! যে ব্যয় করে তাকে প্রতিদান দিন।" অন্যজন বলেন, "হে আল্লাহ! কৃপণের সম্পদ নষ্ট করুন।"',
            reference: 'Sahih al-Bukhari 1442',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَمَا تُنفِقُوا مِنْ خَيْرٍ فَلِأَنفُسِكُمْ',
            textEn: 'And whatever you spend of good - it is for yourselves.',
            textBn: 'আর তোমরা যা কিছু ভালো কাজে ব্যয় কর, তা তোমাদের নিজেদেরই জন্য।',
            reference: 'Al-Baqarah 2:272',
            source: 'Quran',
          ),
        ],
      ),

      // 20. Time Management (Waqt)
      InspirationCategory(
        id: 'time_management',
        nameAr: 'إدارة الوقت',
        nameEn: 'Time Management (Waqt)',
        nameBn: 'সময় ব্যবস্থাপনা (ওয়াক্ত)',
        descriptionAr: 'آيات وأحاديث عن أهمية الوقت وإدارته بحكمة',
        descriptionEn: 'Verses and Hadiths about the importance of time and managing it wisely',
        descriptionBn: 'সময়ের গুরুত্ব এবং বুদ্ধিমত্তার সাথে তার ব্যবস্থাপনা',
        iconPath: '⏰',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَالْعَصْرِ ○ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ ○ إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ',
            textEn: 'By time, indeed mankind is in loss, except for those who have believed and done righteous deeds.',
            textBn: 'যুগের শপথ, নিশ্চয়ই মানুষ ক্ষতিগ্রস্ত, তারা ছাড়া যারা ঈমান এনেছে এবং সৎকর্ম করেছে।',
            reference: 'Al-Asr 103:1-3',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'اغْتَنِمْ خَمْسًا قَبْلَ خَمْسٍ شَبَابَكَ قَبْلَ هَرَمِكَ وَصِحَّتَكَ قَبْلَ سَقَمِكَ وَغِنَاكَ قَبْلَ فَقْرِكَ وَفَرَاغَكَ قَبْلَ شُغُلِكَ وَحَيَاتَكَ قَبْلَ مَوْتِكَ',
            textEn: 'Take advantage of five before five: your youth before your old age, your health before your illness, your wealth before your poverty, your free time before your preoccupation, and your life before your death.',
            textBn: 'পাঁচটি বিষয়কে পাঁচটির আগেই কাজে লাগাও: বার্ধক্যের আগে তারুণ্য, অসুস্থতার আগে সুস্থতা, দারিদ্র্যের আগে সচ্ছলতা, ব্যস্ততার আগে অবসর, মৃত্যুর আগে জীবন।',
            reference: 'Al-Hakim 7846',
            source: 'Hakim',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'نِعْمَتَانِ مَغْبُونٌ فِيهِمَا كَثِيرٌ مِنَ النَّاسِ الصِّحَّةُ وَالْفَرَاغُ',
            textEn: 'There are two blessings which many people lose: health and free time.',
            textBn: 'দুটি নিয়ামত যাতে অনেক মানুষ ক্ষতিগ্রস্ত হয়: স্বাস্থ্য এবং অবসর সময়।',
            reference: 'Sahih al-Bukhari 6412',
            source: 'Bukhari',
          ),
        ],
      ),

      // 21. Family & Relationships (Usrah)
      InspirationCategory(
        id: 'family_relationships',
        nameAr: 'الأسرة والعلاقات',
        nameEn: 'Family & Relationships (Usrah)',
        nameBn: 'পরিবার ও সম্পর্ক (উসরাহ)',
        descriptionAr: 'آيات وأحاديث عن أهمية الأسرة وحقوق الوالدين',
        descriptionEn: 'Verses and Hadiths about the importance of family and parents\' rights',
        descriptionBn: 'পরিবারের গুরুত্ব এবং পিতামাতার অধিকার',
        iconPath: '👪',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَقَضَىٰ رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا',
            textEn: 'And your Lord has decreed that you not worship except Him, and to parents, good treatment.',
            textBn: 'আর তোমার রব নির্দেশ দিয়েছেন যে, তোমরা কেবল তাঁরই ইবাদত করবে এবং পিতামাতার সাথে সদাচরণ করবে।',
            reference: 'Al-Isra 17:23',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'الْجَنَّةُ تَحْتَ أَقْدَامِ الْأُمَّهَاتِ',
            textEn: 'Paradise lies at the feet of mothers.',
            textBn: 'মায়েদের পায়ের নিচে বেহেশত।',
            reference: 'Sunan an-Nasa\'i 3104',
            source: 'Nasa\'i',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً',
            textEn: 'And of His signs is that He created for you from yourselves mates that you may find tranquility in them; and He placed between you affection and mercy.',
            textBn: 'আর তাঁর নিদর্শনাবলীর মধ্যে রয়েছে যে, তিনি তোমাদের জন্য তোমাদের মধ্য থেকেই স্ত্রী সৃষ্টি করেছেন যাতে তোমরা তাদের কাছে শান্তি পাও এবং তোমাদের মধ্যে ভালোবাসা ও দয়া স্থাপন করেছেন।',
            reference: 'Ar-Rum 30:21',
            source: 'Quran',
          ),
        ],
      ),

      // 22. Leadership & Responsibility (Qiyadah)
      InspirationCategory(
        id: 'leadership_responsibility',
        nameAr: 'القيادة والمسؤولية',
        nameEn: 'Leadership & Responsibility (Qiyadah)',
        nameBn: 'নেতৃত্ব ও দায়বদ্ধতা (কিয়াদাহ)',
        descriptionAr: 'آيات وأحاديث عن القيادة والمسؤولية في الإسلام',
        descriptionEn: 'Verses and Hadiths about leadership and responsibility in Islam',
        descriptionBn: 'ইসলামে নেতৃত্ব ও দায়বদ্ধতার গুরুত্ব',
        iconPath: '👑',
        contents: [
          InspirationContent(
            type: 'hadith',
            textAr: 'كُلُّكُمْ رَاعٍ وَكُلُّكُمْ مَسْؤُولٌ عَنْ رَعِيَّتِهِ',
            textEn: 'Every one of you is a shepherd and every one of you is responsible for his flock.',
            textBn: 'তোমাদের প্রত্যেকেই রাখাল এবং প্রত্যেকেই তার পালের জন্য দায়বদ্ধ।',
            reference: 'Sahih al-Bukhari 893',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَجَعَلْنَا مِنْهُمْ أَئِمَّةً يَهْدُونَ بِأَمْرِنَا لَمَّا صَبَرُوا وَكَانُوا بِآيَاتِنَا يُوقِنُونَ',
            textEn: 'And We made from among them leaders guiding by Our command when they were patient and were certain of Our signs.',
            textBn: 'আর আমি তাদের মধ্য থেকে কতক নেতা বানিয়েছিলাম যারা আমার আদেশে পথ প্রদর্শন করত যখন তারা ধৈর্য ধরেছিল এবং আমার নিদর্শনাবলীতে দৃঢ় বিশ্বাস রাখত।',
            reference: 'As-Sajdah 32:24',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَا مِنْ عَبْدٍ يَسْتَرْعِيهِ اللَّهُ رَعِيَّةً يَمُوتُ يَوْمَ يَمُوتُ وَهُوَ غَاشٌّ لِرَعِيَّتِهِ إِلَّا حَرَّمَ اللَّهُ عَلَيْهِ الْجَنَّةَ',
            textEn: 'Any servant whom Allah has put in charge of subjects and dies while he is deceiving them, Allah will forbid Paradise for him.',
            textBn: 'যে ব্যক্তিকে আল্লাহ কোনো দায়িত্ব দিয়েছেন এবং সে তার দায়িত্ব পালনে প্রতারণা করে মৃত্যুবরণ করে, আল্লাহ তার জন্য জান্নাত হারাম করে দেন।',
            reference: 'Sahih Muslim 142',
            source: 'Muslim',
          ),
        ],
      ),

      // 23. Environment & Nature (Bi'ah)
      InspirationCategory(
        id: 'environment_nature',
        nameAr: 'البيئة والطبيعة',
        nameEn: 'Environment & Nature (Bi\'ah)',
        nameBn: 'পরিবেশ ও প্রকৃতি (বিয়াহ)',
        descriptionAr: 'آيات وأحاديث عن حماية البيئة والطبيعة في الإسلام',
        descriptionEn: 'Verses and Hadiths about protecting environment and nature in Islam',
        descriptionBn: 'ইসলামে পরিবেশ ও প্রকৃতি রক্ষার গুরুত্ব',
        iconPath: '🌍',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَهُوَ الَّذِي جَعَلَكُمْ خَلَائِفَ الْأَرْضِ',
            textEn: 'And it is He who has made you successors upon the earth.',
            textBn: 'আর তিনিই তোমাদের পৃথিবীতে প্রতিনিধি করেছেন।',
            reference: 'Fatir 35:39',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَنْ أَحْيَا أَرْضًا مَيْتَةً فَهِيَ لَهُ',
            textEn: 'Whoever revives dead land, it belongs to him.',
            textBn: 'যে মৃত জমি জীবিত করে, তা তারই।',
            reference: 'Sahih al-Bukhari 2335',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنْ قَامَتِ السَّاعَةُ وَفِي يَدِ أَحَدِكُمْ فَسِيلَةٌ فَإِنِ اسْتَطَاعَ أَنْ لَا تَقُومَ حَتَّى يَغْرِسَهَا فَلْيَغْرِسْهَا',
            textEn: 'If the Hour comes while one of you has a palm shoot in his hand, let him plant it if he is able.',
            textBn: 'যদি কিয়ামত এসে যায় আর তোমাদের কারো হাতে একটি চারাগাছ থাকে, তাহলে যদি সে পারে তো তা রোপণ করে দিক।',
            reference: 'Musnad Ahmad 12902',
            source: 'Ahmad',
          ),
        ],
      ),

      // 24. Innovation & Progress (Ibda')
      InspirationCategory(
        id: 'innovation_progress',
        nameAr: 'الابتكار والتقدم',
        nameEn: 'Innovation & Progress (Ibda\')',
        nameBn: 'উদ্ভাবন ও অগ্রগতি (ইবদা)',
        descriptionAr: 'آيات وأحاديث عن التطوير والابتكار والسعي للتقدم',
        descriptionEn: 'Verses and Hadiths about development, innovation, and striving for progress',
        descriptionBn: 'উন্নয়ন, উদ্ভাবন এবং অগ্রগতির জন্য প্রচেষ্টা',
        iconPath: '🚀',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَأَنَّ لَيْسَ لِلْإِنسَانِ إِلَّا مَا سَعَىٰ',
            textEn: 'And that there is nothing for man except what he strives for.',
            textBn: 'আর মানুষের জন্য তা-ই রয়েছে যার জন্য সে চেষ্টা করে।',
            reference: 'An-Najm 53:39',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ',
            textEn: 'Indeed, Allah loves when one of you does a job, he does it with excellence.',
            textBn: 'নিশ্চয়ই আল্লাহ পছন্দ করেন যখন তোমাদের কেউ কোনো কাজ করে, সে তা নিপুণভাবে করুক।',
            reference: 'Shu\'ab al-Iman 4928',
            source: 'Bayhaqi',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَعَلَّمَ آدَمَ الْأَسْمَاءَ كُلَّهَا',
            textEn: 'And He taught Adam the names - all of them.',
            textBn: 'আর তিনি আদমকে সমস্ত নাম শিক্ষা দিলেন।',
            reference: 'Al-Baqarah 2:31',
            source: 'Quran',
          ),
        ],
      ),

      // 25. Hope & Optimism (Raja')
      InspirationCategory(
        id: 'hope_optimism',
        nameAr: 'الأمل والتفاؤل',
        nameEn: 'Hope & Optimism (Raja\')',
        nameBn: 'আশা ও আশাবাদ (রজা)',
        descriptionAr: 'آيات وأحاديث عن الأمل والتفاؤل في الحياة',
        descriptionEn: 'Verses and Hadiths about hope and optimism in life',
        descriptionBn: 'জীবনে আশা ও আশাবাদের গুরুত্ব',
        iconPath: '🌟',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ إِنَّهُ لَا يَيْأَسُ مِن رَّوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ',
            textEn: 'And do not despair of relief from Allah. Indeed, no one despairs of relief from Allah except the disbelieving people.',
            textBn: 'আর তোমরা আল্লাহর রহমত থেকে নিরাশ হয়ো না। নিশ্চয়ই আল্লাহর রহমত থেকে কাফির সম্প্রদায় ছাড়া কেউ নিরাশ হয় না।',
            reference: 'Yusuf 12:87',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'تَفَاءَلُوا بِالْخَيْرِ تَجِدُوهُ',
            textEn: 'Be optimistic about good things and you will find them.',
            textBn: 'ভালো বিষয়ে আশাবাদী হও, তাহলে তা পাবে।',
            reference: 'Al-Mustadrak 7040',
            source: 'Hakim',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَبَشِّرِ الْمُؤْمِنِينَ بِأَنَّ لَهُم مِّنَ اللَّهِ فَضْلًا كَبِيرًا',
            textEn: 'And give good tidings to the believers that they will have from Allah great bounty.',
            textBn: 'আর মুমিনদের সুসংবাদ দাও যে তাদের জন্য আল্লাহর কাছে মহান অনুগ্রহ রয়েছে।',
            reference: 'Al-Ahzab 33:47',
            source: 'Quran',
          ),
        ],
      ),

      // 26. Spiritual Growth (Tazkiyah)
      InspirationCategory(
        id: 'spiritual_growth',
        nameAr: 'النمو الروحي (التزكية)',
        nameEn: 'Spiritual Growth (Tazkiyah)',
        nameBn: 'আধ্যাত্মিক উন্নতি (তাযকিয়াহ)',
        descriptionAr: 'آيات وأحاديث عن تزكية النفس والنمو الروحي',
        descriptionEn: 'Verses and Hadiths about purifying the soul and spiritual development',
        descriptionBn: 'আত্মশুদ্ধি এবং আধ্যাত্মিক উন্নয়ন',
        iconPath: '🌙',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'قَدْ أَفْلَحَ مَن زَكَّاهَا ○ وَقَدْ خَابَ مَن دَسَّاهَا',
            textEn: 'He has succeeded who purifies it, And he has failed who instills it [with corruption].',
            textBn: 'সে সফল হয়েছে যে তা (আত্মাকে) পবিত্র করেছে, আর সে ব্যর্থ হয়েছে যে তাকে কলুষিত করেছে।',
            reference: 'Ash-Shams 91:9-10',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَيُزَكِّيهِمْ وَيُعَلِّمُهُمُ الْكِتَابَ وَالْحِكْمَةَ',
            textEn: 'And purifies them and teaches them the Book and wisdom.',
            textBn: 'আর তাদের পবিত্র করে এবং তাদের কিতাব ও হিকমত শিক্ষা দেয়।',
            reference: 'Al-Baqarah 2:129',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'أَلَا وَإِنَّ فِي الْجَسَدِ مُضْغَةً إِذَا صَلَحَتْ صَلَحَ الْجَسَدُ كُلُّهُ وَإِذَا فَسَدَتْ فَسَدَ الْجَسَدُ كُلُّهُ أَلَا وَهِيَ الْقَلْبُ',
            textEn: 'Indeed, in the body there is a piece of flesh which, if it is sound, the whole body is sound, and if it is corrupt, the whole body is corrupt. Indeed, it is the heart.',
            textBn: 'জেনে রাখো, শরীরে একটি গোশতের টুকরো আছে, যখন তা সুস্থ থাকে, পুরো শরীর সুস্থ থাকে। আর যখন তা নষ্ট হয়, পুরো শরীর নষ্ট হয়। জেনে রাখো, সেটা হলো হৃদয়।',
            reference: 'Sahih al-Bukhari 52',
            source: 'Bukhari',
          ),
        ],
      ),

      // 27. Courage & Bravery (Shuja'ah)
      InspirationCategory(
        id: 'courage_bravery',
        nameAr: 'الشجاعة والبسالة',
        nameEn: 'Courage & Bravery (Shuja\'ah)',
        nameBn: 'সাহস ও বীরত্ব (শুজায়াহ)',
        descriptionAr: 'آيات وأحاديث عن الشجاعة والثبات في وجه التحديات',
        descriptionEn: 'Verses and Hadiths about courage and steadfastness in facing challenges',
        descriptionBn: 'চ্যালেঞ্জের মুখে সাহস ও দৃঢ়তার গুরুত্ব',
        iconPath: '🦁',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'فَمَن يُؤْمِن بِرَبِّهِ فَلَا يَخَافُ بَخْسًا وَلَا رَهَقًا',
            textEn: 'So whoever believes in his Lord will not fear deprivation or burden.',
            textBn: 'অতএব যে তার রবের প্রতি ঈমান আনে, সে কোনো ক্ষতি বা জুলুমের ভয় করে না।',
            reference: 'Al-Jinn 72:13',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ',
            textEn: 'The strong believer is better and more beloved to Allah than the weak believer.',
            textBn: 'শক্তিশালী মুমিন দুর্বল মুমিনের চেয়ে উত্তম এবং আল্লাহর কাছে অধিক প্রিয়।',
            reference: 'Sahih Muslim 2664',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنتُمُ الْأَعْلَوْنَ إِن كُنتُم مُّؤْمِنِينَ',
            textEn: 'So do not weaken and do not grieve, and you will be superior if you are [true] believers.',
            textBn: 'তোমরা হতোৎসাহ হয়ো না এবং দুঃখ করো না। তোমরাই বিজয়ী হবে যদি তোমরা সত্যিকারের মুমিন হও।',
            reference: 'Ali \'Imran 3:139',
            source: 'Quran',
          ),
        ],
      ),

      // 28. Wisdom & Reflection (Hikmah)
      InspirationCategory(
        id: 'wisdom_reflection',
        nameAr: 'الحكمة والتأمل',
        nameEn: 'Wisdom & Reflection (Hikmah)',
        nameBn: 'জ্ঞান ও চিন্তা-ভাবনা (হিকমাহ)',
        descriptionAr: 'آيات وأحاديث عن الحكمة والتفكر في خلق الله',
        descriptionEn: 'Verses and Hadiths about wisdom and contemplation of Allah\'s creation',
        descriptionBn: 'প্রজ্ঞা এবং আল্লাহর সৃষ্টি নিয়ে চিন্তা-ভাবনা',
        iconPath: '🧠',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'يُؤْتِي الْحِكْمَةَ مَن يَشَاءُ وَمَن يُؤْتَ الْحِكْمَةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا',
            textEn: 'He gives wisdom to whom He wills, and whoever has been given wisdom has certainly been given much good.',
            textBn: 'তিনি যাকে ইচ্ছা প্রজ্ঞা দান করেন এবং যাকে প্রজ্ঞা দান করা হয় তাকে অবশ্যই প্রভূত কল্যাণ দেওয়া হয়।',
            reference: 'Al-Baqarah 2:269',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِّأُولِي الْأَلْبَابِ',
            textEn: 'Indeed, in the creation of the heavens and earth and the alternation of the night and day are signs for those of understanding.',
            textBn: 'নিশ্চয়ই আকাশ ও পৃথিবীর সৃষ্টিতে এবং রাত ও দিনের পরিবর্তনে জ্ঞানীদের জন্য নিদর্শন রয়েছে।',
            reference: 'Ali \'Imran 3:190',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'سَاعَةُ تَفَكُّرٍ خَيْرٌ مِنْ سَبْعِينَ سَنَةِ عِبَادَةٍ',
            textEn: 'An hour of reflection is better than seventy years of worship.',
            textBn: 'এক ঘণ্টার চিন্তা-ভাবনা সত্তর বছরের ইবাদতের চেয়ে উত্তম।',
            reference: 'Al-Firdaws 8635',
            source: 'Daylami',
          ),
        ],
      ),

      // 29. Hospitality & Kindness (Karam)
      InspirationCategory(
        id: 'hospitality_kindness',
        nameAr: 'الضيافة واللطف',
        nameEn: 'Hospitality & Kindness (Karam)',
        nameBn: 'আতিথেয়তা ও দয়া (কারাম)',
        descriptionAr: 'آيات وأحاديث عن كرم الضيافة والإحسان إلى الناس',
        descriptionEn: 'Verses and Hadiths about generous hospitality and kindness to people',
        descriptionBn: 'উদার আতিথেয়তা এবং মানুষের প্রতি দয়ার গুরুত্ব',
        iconPath: '🤗',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَيُؤْثِرُونَ عَلَىٰ أَنفُسِهِمْ وَلَوْ كَانَ بِهِمْ خَصَاصَةٌ',
            textEn: 'And [they] give [them] preference over themselves, even though they are in privation.',
            textBn: 'আর তারা নিজেদের অভাব থাকা সত্ত্বেও অন্যদের অগ্রাধিকার দেয়।',
            reference: 'Al-Hashr 59:9',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيُكْرِمْ ضَيْفَهُ',
            textEn: 'Whoever believes in Allah and the Last Day should honor his guest.',
            textBn: 'যে আল্লাহ ও পরকালে বিশ্বাস করে, সে যেন তার মেহমানকে সম্মান করে।',
            reference: 'Sahih al-Bukhari 6019',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'وَخَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ',
            textEn: 'The best of people are those who are most beneficial to others.',
            textBn: 'মানুষের মধ্যে সবচেয়ে ভালো তারা যারা অন্যদের জন্য সবচেয়ে উপকারী।',
            reference: 'Shu\'ab al-Iman 7225',
            source: 'Bayhaqi',
          ),
        ],
      ),

      // 30. Purification & Cleanliness (Taharah)
      InspirationCategory(
        id: 'purification_cleanliness',
        nameAr: 'الطهارة والنظافة',
        nameEn: 'Purification & Cleanliness (Taharah)',
        nameBn: 'পবিত্রতা ও পরিচ্ছন্নতা (তাহারাহ)',
        descriptionAr: 'آيات وأحاديث عن الطهارة البدنية والروحية',
        descriptionEn: 'Verses and Hadiths about physical and spiritual purification',
        descriptionBn: 'শারীরিক ও আধ্যাত্মিক পবিত্রতার গুরুত্ব',
        iconPath: '🧼',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ',
            textEn: 'Indeed, Allah loves those who are constantly repentant and loves those who purify themselves.',
            textBn: 'নিশ্চয়ই আল্লাহ তওবাকারীদের ভালোবাসেন এবং পবিত্রতা অর্জনকারীদের ভালোবাসেন।',
            reference: 'Al-Baqarah 2:222',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'الطَّهُورُ شَطْرُ الْإِيمَانِ',
            textEn: 'Purification is half of faith.',
            textBn: 'পবিত্রতা ঈমানের অর্ধেক।',
            reference: 'Sahih Muslim 223',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنَّ اللَّهَ طَيِّبٌ يُحِبُّ الطَّيِّبَ نَظِيفٌ يُحِبُّ النَّظَافَةَ',
            textEn: 'Indeed, Allah is pure and loves purity, clean and loves cleanliness.',
            textBn: 'নিশ্চয়ই আল্লাহ পবিত্র এবং পবিত্রতা ভালোবাসেন, পরিচ্ছন্ন এবং পরিচ্ছন্নতা ভালোবাসেন।',
            reference: 'Jami\' at-Tirmidhi 2799',
            source: 'Tirmidhi',
          ),
        ],
      ),

      // 31. Business & Ethics (Tijara)
      InspirationCategory(
        id: 'business_ethics',
        nameAr: 'التجارة والأخلاق',
        nameEn: 'Business & Ethics (Tijara)',
        nameBn: 'ব্যবসা ও নৈতিকতা (তিজারাহ)',
        descriptionAr: 'آيات وأحاديث عن الأخلاق في التجارة والأمانة',
        descriptionEn: 'Verses and Hadiths about ethics in business and trustworthiness',
        descriptionBn: 'ব্যবসায় নৈতিকতা এবং বিশ্বস্ততার গুরুত্ব',
        iconPath: '💼',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَأَوْفُوا الْكَيْلَ وَالْمِيزَانَ بِالْقِسْطِ',
            textEn: 'And give full measure and weight in justice.',
            textBn: 'আর ন্যায়ের সাথে পূর্ণ মাপ ও ওজন দাও।',
            reference: 'Al-An\'am 6:152',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'التَّاجِرُ الصَّدُوقُ الْأَمِينُ مَعَ النَّبِيِّينَ وَالصِّدِّيقِينَ وَالشُّهَدَاءِ',
            textEn: 'The truthful and trustworthy merchant will be with the prophets, the truthful and the martyrs.',
            textBn: 'সৎ ও বিশ্বস্ত ব্যবসায়ী নবী, সিদ্দীক ও শহীদদের সাথে থাকবে।',
            reference: 'Jami\' at-Tirmidhi 1209',
            source: 'Tirmidhi',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَيْلٌ لِّلْمُطَفِّفِينَ ○ الَّذِينَ إِذَا اكْتَالُوا عَلَى النَّاسِ يَسْتَوْفُونَ ○ وَإِذَا كَالُوهُمْ أَو وَّزَنُوهُمْ يُخْسِرُونَ',
            textEn: 'Woe to those who give less [than due], Who, when they take a measure from people, take in full. But if they give by measure or by weight to them, they cause loss.',
            textBn: 'দুর্ভোগ তাদের জন্য যারা মাপে কম দেয়। যারা লোকদের কাছ থেকে নিলে পূর্ণ মাত্রায় নেয় কিন্তু যখন তাদের মেপে বা ওজন করে দেয় তখন কম দেয়।',
            reference: 'Al-Mutaffifin 83:1-3',
            source: 'Quran',
          ),
        ],
      ),

      // 32. Travel & Journey (Safar)
      InspirationCategory(
        id: 'travel_journey',
        nameAr: 'السفر والرحلة',
        nameEn: 'Travel & Journey (Safar)',
        nameBn: 'ভ্রমণ ও যাত্রা (সাফার)',
        descriptionAr: 'آيات وأحاديث عن السفر وآدابه في الإسلام',
        descriptionEn: 'Verses and Hadiths about travel and its etiquettes in Islam',
        descriptionBn: 'ইসলামে ভ্রমণ এবং তার আদবের গুরুত্ব',
        iconPath: '🧳',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'قُلْ سِيرُوا فِي الْأَرْضِ فَانظُرُوا كَيْفَ بَدَأَ الْخَلْقَ',
            textEn: 'Say, "Travel through the land and observe how He began creation."',
            textBn: 'বল, তোমরা পৃথিবীতে ভ্রমণ কর এবং দেখো কিভাবে তিনি সৃষ্টি শুরু করেছেন।',
            reference: 'Al-Ankabut 29:20',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'السَّفَرُ قِطْعَةٌ مِنَ الْعَذَابِ',
            textEn: 'Travel is a piece of torture.',
            textBn: 'ভ্রমণ যন্ত্রণার একটি অংশ।',
            reference: 'Sahih al-Bukhari 1804',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الْأَهْلِ',
            textEn: 'O Allah, You are the companion on the journey and the successor over the family.',
            textBn: 'হে আল্লাহ, আপনি সফরের সঙ্গী এবং পরিবারের তত্ত্বাবধায়ক।',
            reference: 'Sahih Muslim 1342',
            source: 'Muslim',
          ),
        ],
      ),

      // 33. Marriage & Partnership (Zawaj)
      InspirationCategory(
        id: 'marriage_partnership',
        nameAr: 'الزواج والشراكة',
        nameEn: 'Marriage & Partnership (Zawaj)',
        nameBn: 'বিবাহ ও অংশীদারিত্ব (যাওয়াজ)',
        descriptionAr: 'آيات وأحاديث عن الزواج والحياة الزوجية الصالحة',
        descriptionEn: 'Verses and Hadiths about marriage and righteous married life',
        descriptionBn: 'বিবাহ এবং ভালো দাম্পত্য জীবনের গুরুত্ব',
        iconPath: '💍',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'هُنَّ لِبَاسٌ لَّكُمْ وَأَنتُمْ لِبَاسٌ لَّهُنَّ',
            textEn: 'They are clothing for you and you are clothing for them.',
            textBn: 'তারা তোমাদের পোশাক এবং তোমরা তাদের পোশাক।',
            reference: 'Al-Baqarah 2:187',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ وَأَنَا خَيْرُكُمْ لِأَهْلِي',
            textEn: 'The best of you are those who are best to their families, and I am the best of you to my family.',
            textBn: 'তোমাদের মধ্যে সবচেয়ে ভালো সেই ব্যক্তি যে তার পরিবারের কাছে সবচেয়ে ভালো। আর আমি আমার পরিবারের কাছে তোমাদের মধ্যে সবচেয়ে ভালো।',
            reference: 'Jami\' at-Tirmidhi 3895',
            source: 'Tirmidhi',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِذَا تَزَوَّجَ الْعَبْدُ فَقَدِ اسْتَكْمَلَ نِصْفَ دِينِهِ',
            textEn: 'When a servant gets married, he has completed half of his religion.',
            textBn: 'যখন কোনো বান্দা বিবাহ করে, সে তার দীনের অর্ধেক পূর্ণ করে।',
            reference: 'Shu\'ab al-Iman 5486',
            source: 'Bayhaqi',
          ),
        ],
      ),

      // 34. Community Service (Khidmah)
      InspirationCategory(
        id: 'community_service',
        nameAr: 'خدمة المجتمع',
        nameEn: 'Community Service (Khidmah)',
        nameBn: 'সমাজসেবা (খিদমাহ)',
        descriptionAr: 'آيات وأحاديث عن خدمة المجتمع والعمل التطوعي',
        descriptionEn: 'Verses and Hadiths about community service and volunteer work',
        descriptionBn: 'সমাজসেবা এবং স্বেচ্ছাসেবী কাজের গুরুত্ব',
        iconPath: '🤝',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ وَلَا تَعَاوَنُوا عَلَى الْإِثْمِ وَالْعُدْوَانِ',
            textEn: 'And cooperate in righteousness and piety, but do not cooperate in sin and aggression.',
            textBn: 'আর তোমরা সৎকাজ ও তাকওয়ায় পরস্পরকে সহযোগিতা কর এবং পাপ ও সীমালঙ্ঘনে পরস্পরকে সহযোগিতা করো না।',
            reference: 'Al-Ma\'idah 5:2',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ',
            textEn: 'Whoever relieves a believer\'s distress of the distressful aspects of this world, Allah will rescue him from a difficulty of the difficulties of the Hereafter.',
            textBn: 'যে ব্যক্তি কোনো মুমিনের পার্থিব কষ্ট দূর করে, আল্লাহ তার পরকালের কোনো কষ্ট দূর করবেন।',
            reference: 'Sahih Muslim 2699',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مَنْ كَانَ فِي حَاجَةِ أَخِيهِ كَانَ اللَّهُ فِي حَاجَتِهِ',
            textEn: 'Whoever fulfills the needs of his brother, Allah will fulfill his needs.',
            textBn: 'যে তার ভাইের প্রয়োজন পূরণ করে, আল্লাহ তার প্রয়োজন পূরণ করেন।',
            reference: 'Sahih al-Bukhari 2442',
            source: 'Bukhari',
          ),
        ],
      ),

      // 35. Youth & Education (Shabab)
      InspirationCategory(
        id: 'youth_education',
        nameAr: 'الشباب والتربية',
        nameEn: 'Youth & Education (Shabab)',
        nameBn: 'যুবক ও শিক্ষা (শাবাব)',
        descriptionAr: 'آيات وأحاديث عن أهمية الشباب وتعليمهم',
        descriptionEn: 'Verses and Hadiths about the importance of youth and their education',
        descriptionBn: 'যুবকদের গুরুত্ব এবং তাদের শিক্ষার প্রয়োজনীয়তা',
        iconPath: '🎓',
        contents: [
          InspirationContent(
            type: 'hadith',
            textAr: 'سَبْعَةٌ يُظِلُّهُمُ اللَّهُ فِي ظِلِّهِ يَوْمَ لَا ظِلَّ إِلَّا ظِلُّهُ وَشَابٌّ نَشَأَ فِي عِبَادَةِ اللَّهِ',
            textEn: 'Seven will be shaded by Allah under His shade on the Day when there is no shade except His shade: a youth who grew up in the worship of Allah.',
            textBn: 'সাতজনকে আল্লাহ তাঁর ছায়ায় ছায়া দেবেন যেদিন তাঁর ছায়া ছাড়া কোনো ছায়া থাকবে না: এমন যুবক যে আল্লাহর ইবাদতে বেড়ে উঠেছে।',
            reference: 'Sahih al-Bukhari 660',
            source: 'Bukhari',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'وَوَصَّيْنَا الْإِنسَانَ بِوَالِدَيْهِ إِحْسَانًا',
            textEn: 'And We have enjoined upon man goodness to parents.',
            textBn: 'আর আমি মানুষকে তার পিতামাতার সাথে সদাচরণের নির্দেশ দিয়েছি।',
            reference: 'Al-Ahqaf 46:15',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'مُرُوا أَوْلَادَكُمْ بِالصَّلَاةِ وَهُمْ أَبْنَاءُ سَبْعِ سِنِينَ',
            textEn: 'Command your children to pray when they become seven years old.',
            textBn: 'তোমাদের সন্তানরা সাত বছর বয়সে পৌঁছলে তাদের নামাযের আদেশ দাও।',
            reference: 'Sunan Abi Dawud 495',
            source: 'Abu Dawud',
          ),
        ],
      ),

      // 36. Art & Creativity (Fann)
      InspirationCategory(
        id: 'art_creativity',
        nameAr: 'الفن والإبداع',
        nameEn: 'Art & Creativity (Fann)',
        nameBn: 'শিল্প ও সৃজনশীলতা (ফান্ন)',
        descriptionAr: 'آيات وأحاديث عن الجمال والإبداع في الإسلام',
        descriptionEn: 'Verses and Hadiths about beauty and creativity in Islam',
        descriptionBn: 'ইসলামে সৌন্দর্য ও সৃজনশীলতার গুরুত্ব',
        iconPath: '🎨',
        contents: [
          InspirationContent(
            type: 'verse',
            textAr: 'وَلَقَدْ كَرَّمْنَا بَنِي آدَمَ',
            textEn: 'And We have certainly honored the children of Adam.',
            textBn: 'আর নিশ্চয়ই আমি আদম সন্তানদের সম্মানিত করেছি।',
            reference: 'Al-Isra 17:70',
            source: 'Quran',
          ),
          InspirationContent(
            type: 'hadith',
            textAr: 'إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ',
            textEn: 'Indeed, Allah is beautiful and He loves beauty.',
            textBn: 'নিশ্চয়ই আল্লাহ সুন্দর এবং তিনি সৌন্দর্য ভালোবাসেন।',
            reference: 'Sahih Muslim 91',
            source: 'Muslim',
          ),
          InspirationContent(
            type: 'verse',
            textAr: 'الَّذِي أَحْسَنَ كُلَّ شَيْءٍ خَلَقَهُ',
            textEn: 'Who perfected everything which He created.',
            textBn: 'যিনি তাঁর সৃষ্ট প্রতিটি বস্তুকে সুন্দর করেছেন।',
            reference: 'As-Sajdah 32:7',
            source: 'Quran',
          ),
        ],
      ),
    ];
  }
}